// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/client/account"
	"github.com/trishtzy/go-paradex/client/algos"
	"github.com/trishtzy/go-paradex/client/authentication"
	"github.com/trishtzy/go-paradex/client/insurance"
	"github.com/trishtzy/go-paradex/client/liquidations"
	"github.com/trishtzy/go-paradex/client/markets"
	"github.com/trishtzy/go-paradex/client/orders"
	"github.com/trishtzy/go-paradex/client/referrals"
	"github.com/trishtzy/go-paradex/client/system"
	"github.com/trishtzy/go-paradex/client/trades"
	"github.com/trishtzy/go-paradex/client/transfers"
	"github.com/trishtzy/go-paradex/client/vaults"
)

// Default paradex r e s t API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.testnet.paradex.trade"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/v1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new paradex r e s t API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ParadexRESTAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new paradex r e s t API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *ParadexRESTAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new paradex r e s t API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *ParadexRESTAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(ParadexRESTAPI)
	cli.Transport = transport
	cli.Account = account.New(transport, formats)
	cli.Algos = algos.New(transport, formats)
	cli.Authentication = authentication.New(transport, formats)
	cli.Insurance = insurance.New(transport, formats)
	cli.Liquidations = liquidations.New(transport, formats)
	cli.Markets = markets.New(transport, formats)
	cli.Orders = orders.New(transport, formats)
	cli.Referrals = referrals.New(transport, formats)
	cli.System = system.New(transport, formats)
	cli.Trades = trades.New(transport, formats)
	cli.Transfers = transfers.New(transport, formats)
	cli.Vaults = vaults.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// ParadexRESTAPI is a client for paradex r e s t API
type ParadexRESTAPI struct {
	Account account.ClientService

	Algos algos.ClientService

	Authentication authentication.ClientService

	Insurance insurance.ClientService

	Liquidations liquidations.ClientService

	Markets markets.ClientService

	Orders orders.ClientService

	Referrals referrals.ClientService

	System system.ClientService

	Trades trades.ClientService

	Transfers transfers.ClientService

	Vaults vaults.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ParadexRESTAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Account.SetTransport(transport)
	c.Algos.SetTransport(transport)
	c.Authentication.SetTransport(transport)
	c.Insurance.SetTransport(transport)
	c.Liquidations.SetTransport(transport)
	c.Markets.SetTransport(transport)
	c.Orders.SetTransport(transport)
	c.Referrals.SetTransport(transport)
	c.System.SetTransport(transport)
	c.Trades.SetTransport(transport)
	c.Transfers.SetTransport(transport)
	c.Vaults.SetTransport(transport)
}
