// Code generated by go-swagger; DO NOT EDIT.

package algos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// CreateAlgoOrderReader is a Reader for the CreateAlgoOrder structure.
type CreateAlgoOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAlgoOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateAlgoOrderCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAlgoOrderBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /algo/orders] create-algo-order", response, response.Code())
	}
}

// NewCreateAlgoOrderCreated creates a CreateAlgoOrderCreated with default headers values
func NewCreateAlgoOrderCreated() *CreateAlgoOrderCreated {
	return &CreateAlgoOrderCreated{}
}

/*
CreateAlgoOrderCreated describes a response with status code 201, with default header values.

Created
*/
type CreateAlgoOrderCreated struct {
	Payload *models.ResponsesAlgoOrderResp
}

// IsSuccess returns true when this create algo order created response has a 2xx status code
func (o *CreateAlgoOrderCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create algo order created response has a 3xx status code
func (o *CreateAlgoOrderCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create algo order created response has a 4xx status code
func (o *CreateAlgoOrderCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create algo order created response has a 5xx status code
func (o *CreateAlgoOrderCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create algo order created response a status code equal to that given
func (o *CreateAlgoOrderCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create algo order created response
func (o *CreateAlgoOrderCreated) Code() int {
	return 201
}

func (o *CreateAlgoOrderCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /algo/orders][%d] createAlgoOrderCreated %s", 201, payload)
}

func (o *CreateAlgoOrderCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /algo/orders][%d] createAlgoOrderCreated %s", 201, payload)
}

func (o *CreateAlgoOrderCreated) GetPayload() *models.ResponsesAlgoOrderResp {
	return o.Payload
}

func (o *CreateAlgoOrderCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAlgoOrderResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAlgoOrderBadRequest creates a CreateAlgoOrderBadRequest with default headers values
func NewCreateAlgoOrderBadRequest() *CreateAlgoOrderBadRequest {
	return &CreateAlgoOrderBadRequest{}
}

/*
CreateAlgoOrderBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateAlgoOrderBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this create algo order bad request response has a 2xx status code
func (o *CreateAlgoOrderBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create algo order bad request response has a 3xx status code
func (o *CreateAlgoOrderBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create algo order bad request response has a 4xx status code
func (o *CreateAlgoOrderBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create algo order bad request response has a 5xx status code
func (o *CreateAlgoOrderBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create algo order bad request response a status code equal to that given
func (o *CreateAlgoOrderBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create algo order bad request response
func (o *CreateAlgoOrderBadRequest) Code() int {
	return 400
}

func (o *CreateAlgoOrderBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /algo/orders][%d] createAlgoOrderBadRequest %s", 400, payload)
}

func (o *CreateAlgoOrderBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /algo/orders][%d] createAlgoOrderBadRequest %s", 400, payload)
}

func (o *CreateAlgoOrderBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *CreateAlgoOrderBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
