// Code generated by go-swagger; DO NOT EDIT.

package algos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetAlgoOrdersHistoryReader is a Reader for the GetAlgoOrdersHistory structure.
type GetAlgoOrdersHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlgoOrdersHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlgoOrdersHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAlgoOrdersHistoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /algo/orders-history] get-algo-orders-history", response, response.Code())
	}
}

// NewGetAlgoOrdersHistoryOK creates a GetAlgoOrdersHistoryOK with default headers values
func NewGetAlgoOrdersHistoryOK() *GetAlgoOrdersHistoryOK {
	return &GetAlgoOrdersHistoryOK{}
}

/*
GetAlgoOrdersHistoryOK describes a response with status code 200, with default header values.

OK
*/
type GetAlgoOrdersHistoryOK struct {
	Payload *models.ResponsesGetAlgoOrders
}

// IsSuccess returns true when this get algo orders history o k response has a 2xx status code
func (o *GetAlgoOrdersHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get algo orders history o k response has a 3xx status code
func (o *GetAlgoOrdersHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get algo orders history o k response has a 4xx status code
func (o *GetAlgoOrdersHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get algo orders history o k response has a 5xx status code
func (o *GetAlgoOrdersHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get algo orders history o k response a status code equal to that given
func (o *GetAlgoOrdersHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get algo orders history o k response
func (o *GetAlgoOrdersHistoryOK) Code() int {
	return 200
}

func (o *GetAlgoOrdersHistoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /algo/orders-history][%d] getAlgoOrdersHistoryOK %s", 200, payload)
}

func (o *GetAlgoOrdersHistoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /algo/orders-history][%d] getAlgoOrdersHistoryOK %s", 200, payload)
}

func (o *GetAlgoOrdersHistoryOK) GetPayload() *models.ResponsesGetAlgoOrders {
	return o.Payload
}

func (o *GetAlgoOrdersHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetAlgoOrders)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAlgoOrdersHistoryBadRequest creates a GetAlgoOrdersHistoryBadRequest with default headers values
func NewGetAlgoOrdersHistoryBadRequest() *GetAlgoOrdersHistoryBadRequest {
	return &GetAlgoOrdersHistoryBadRequest{}
}

/*
GetAlgoOrdersHistoryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAlgoOrdersHistoryBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get algo orders history bad request response has a 2xx status code
func (o *GetAlgoOrdersHistoryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get algo orders history bad request response has a 3xx status code
func (o *GetAlgoOrdersHistoryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get algo orders history bad request response has a 4xx status code
func (o *GetAlgoOrdersHistoryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get algo orders history bad request response has a 5xx status code
func (o *GetAlgoOrdersHistoryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get algo orders history bad request response a status code equal to that given
func (o *GetAlgoOrdersHistoryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get algo orders history bad request response
func (o *GetAlgoOrdersHistoryBadRequest) Code() int {
	return 400
}

func (o *GetAlgoOrdersHistoryBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /algo/orders-history][%d] getAlgoOrdersHistoryBadRequest %s", 400, payload)
}

func (o *GetAlgoOrdersHistoryBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /algo/orders-history][%d] getAlgoOrdersHistoryBadRequest %s", 400, payload)
}

func (o *GetAlgoOrdersHistoryBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetAlgoOrdersHistoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
