// Code generated by go-swagger; DO NOT EDIT.

package referrals

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetReferralsSummaryReader is a Reader for the GetReferralsSummary structure.
type GetReferralsSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReferralsSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReferralsSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetReferralsSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetReferralsSummaryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /referrals/summary] get-referrals-summary", response, response.Code())
	}
}

// NewGetReferralsSummaryOK creates a GetReferralsSummaryOK with default headers values
func NewGetReferralsSummaryOK() *GetReferralsSummaryOK {
	return &GetReferralsSummaryOK{}
}

/*
GetReferralsSummaryOK describes a response with status code 200, with default header values.

OK
*/
type GetReferralsSummaryOK struct {
	Payload *models.ResponsesGetReferrals
}

// IsSuccess returns true when this get referrals summary o k response has a 2xx status code
func (o *GetReferralsSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get referrals summary o k response has a 3xx status code
func (o *GetReferralsSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get referrals summary o k response has a 4xx status code
func (o *GetReferralsSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get referrals summary o k response has a 5xx status code
func (o *GetReferralsSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get referrals summary o k response a status code equal to that given
func (o *GetReferralsSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get referrals summary o k response
func (o *GetReferralsSummaryOK) Code() int {
	return 200
}

func (o *GetReferralsSummaryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryOK %s", 200, payload)
}

func (o *GetReferralsSummaryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryOK %s", 200, payload)
}

func (o *GetReferralsSummaryOK) GetPayload() *models.ResponsesGetReferrals {
	return o.Payload
}

func (o *GetReferralsSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetReferrals)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReferralsSummaryBadRequest creates a GetReferralsSummaryBadRequest with default headers values
func NewGetReferralsSummaryBadRequest() *GetReferralsSummaryBadRequest {
	return &GetReferralsSummaryBadRequest{}
}

/*
GetReferralsSummaryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetReferralsSummaryBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get referrals summary bad request response has a 2xx status code
func (o *GetReferralsSummaryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get referrals summary bad request response has a 3xx status code
func (o *GetReferralsSummaryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get referrals summary bad request response has a 4xx status code
func (o *GetReferralsSummaryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get referrals summary bad request response has a 5xx status code
func (o *GetReferralsSummaryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get referrals summary bad request response a status code equal to that given
func (o *GetReferralsSummaryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get referrals summary bad request response
func (o *GetReferralsSummaryBadRequest) Code() int {
	return 400
}

func (o *GetReferralsSummaryBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryBadRequest %s", 400, payload)
}

func (o *GetReferralsSummaryBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryBadRequest %s", 400, payload)
}

func (o *GetReferralsSummaryBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetReferralsSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReferralsSummaryUnauthorized creates a GetReferralsSummaryUnauthorized with default headers values
func NewGetReferralsSummaryUnauthorized() *GetReferralsSummaryUnauthorized {
	return &GetReferralsSummaryUnauthorized{}
}

/*
GetReferralsSummaryUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetReferralsSummaryUnauthorized struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get referrals summary unauthorized response has a 2xx status code
func (o *GetReferralsSummaryUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get referrals summary unauthorized response has a 3xx status code
func (o *GetReferralsSummaryUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get referrals summary unauthorized response has a 4xx status code
func (o *GetReferralsSummaryUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get referrals summary unauthorized response has a 5xx status code
func (o *GetReferralsSummaryUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get referrals summary unauthorized response a status code equal to that given
func (o *GetReferralsSummaryUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get referrals summary unauthorized response
func (o *GetReferralsSummaryUnauthorized) Code() int {
	return 401
}

func (o *GetReferralsSummaryUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryUnauthorized %s", 401, payload)
}

func (o *GetReferralsSummaryUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /referrals/summary][%d] getReferralsSummaryUnauthorized %s", 401, payload)
}

func (o *GetReferralsSummaryUnauthorized) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetReferralsSummaryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
