// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetSystemStateReader is a Reader for the GetSystemState structure.
type GetSystemStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /system/state] GetSystemState", response, response.Code())
	}
}

// NewGetSystemStateOK creates a GetSystemStateOK with default headers values
func NewGetSystemStateOK() *GetSystemStateOK {
	return &GetSystemStateOK{}
}

/*
GetSystemStateOK describes a response with status code 200, with default header values.

OK
*/
type GetSystemStateOK struct {
	Payload *models.ResponsesSystemStateResponse
}

// IsSuccess returns true when this get system state o k response has a 2xx status code
func (o *GetSystemStateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get system state o k response has a 3xx status code
func (o *GetSystemStateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get system state o k response has a 4xx status code
func (o *GetSystemStateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get system state o k response has a 5xx status code
func (o *GetSystemStateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get system state o k response a status code equal to that given
func (o *GetSystemStateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get system state o k response
func (o *GetSystemStateOK) Code() int {
	return 200
}

func (o *GetSystemStateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/state][%d] getSystemStateOK %s", 200, payload)
}

func (o *GetSystemStateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/state][%d] getSystemStateOK %s", 200, payload)
}

func (o *GetSystemStateOK) GetPayload() *models.ResponsesSystemStateResponse {
	return o.Payload
}

func (o *GetSystemStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesSystemStateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
