// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSystemTimeParams creates a new GetSystemTimeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSystemTimeParams() *GetSystemTimeParams {
	return &GetSystemTimeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSystemTimeParamsWithTimeout creates a new GetSystemTimeParams object
// with the ability to set a timeout on a request.
func NewGetSystemTimeParamsWithTimeout(timeout time.Duration) *GetSystemTimeParams {
	return &GetSystemTimeParams{
		timeout: timeout,
	}
}

// NewGetSystemTimeParamsWithContext creates a new GetSystemTimeParams object
// with the ability to set a context for a request.
func NewGetSystemTimeParamsWithContext(ctx context.Context) *GetSystemTimeParams {
	return &GetSystemTimeParams{
		Context: ctx,
	}
}

// NewGetSystemTimeParamsWithHTTPClient creates a new GetSystemTimeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSystemTimeParamsWithHTTPClient(client *http.Client) *GetSystemTimeParams {
	return &GetSystemTimeParams{
		HTTPClient: client,
	}
}

/*
GetSystemTimeParams contains all the parameters to send to the API endpoint

	for the get system time operation.

	Typically these are written to a http.Request.
*/
type GetSystemTimeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get system time params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemTimeParams) WithDefaults() *GetSystemTimeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get system time params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSystemTimeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get system time params
func (o *GetSystemTimeParams) WithTimeout(timeout time.Duration) *GetSystemTimeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get system time params
func (o *GetSystemTimeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get system time params
func (o *GetSystemTimeParams) WithContext(ctx context.Context) *GetSystemTimeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get system time params
func (o *GetSystemTimeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get system time params
func (o *GetSystemTimeParams) WithHTTPClient(client *http.Client) *GetSystemTimeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get system time params
func (o *GetSystemTimeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemTimeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
