// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetSystemConfigReader is a Reader for the GetSystemConfig structure.
type GetSystemConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSystemConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSystemConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /system/config] GetSystemConfig", response, response.Code())
	}
}

// NewGetSystemConfigOK creates a GetSystemConfigOK with default headers values
func NewGetSystemConfigOK() *GetSystemConfigOK {
	return &GetSystemConfigOK{}
}

/*
GetSystemConfigOK describes a response with status code 200, with default header values.

OK
*/
type GetSystemConfigOK struct {
	Payload *models.ResponsesSystemConfigResponse
}

// IsSuccess returns true when this get system config o k response has a 2xx status code
func (o *GetSystemConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get system config o k response has a 3xx status code
func (o *GetSystemConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get system config o k response has a 4xx status code
func (o *GetSystemConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get system config o k response has a 5xx status code
func (o *GetSystemConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get system config o k response a status code equal to that given
func (o *GetSystemConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get system config o k response
func (o *GetSystemConfigOK) Code() int {
	return 200
}

func (o *GetSystemConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/config][%d] getSystemConfigOK %s", 200, payload)
}

func (o *GetSystemConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /system/config][%d] getSystemConfigOK %s", 200, payload)
}

func (o *GetSystemConfigOK) GetPayload() *models.ResponsesSystemConfigResponse {
	return o.Payload
}

func (o *GetSystemConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesSystemConfigResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
