// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// VaultsGetTransfersReader is a Reader for the VaultsGetTransfers structure.
type VaultsGetTransfersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VaultsGetTransfersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVaultsGetTransfersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVaultsGetTransfersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /vaults/transfers] vaults-get-transfers", response, response.Code())
	}
}

// NewVaultsGetTransfersOK creates a VaultsGetTransfersOK with default headers values
func NewVaultsGetTransfersOK() *VaultsGetTransfersOK {
	return &VaultsGetTransfersOK{}
}

/*
VaultsGetTransfersOK describes a response with status code 200, with default header values.

OK
*/
type VaultsGetTransfersOK struct {
	Payload *models.ResponsesVaultTransfersResp
}

// IsSuccess returns true when this vaults get transfers o k response has a 2xx status code
func (o *VaultsGetTransfersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vaults get transfers o k response has a 3xx status code
func (o *VaultsGetTransfersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get transfers o k response has a 4xx status code
func (o *VaultsGetTransfersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vaults get transfers o k response has a 5xx status code
func (o *VaultsGetTransfersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get transfers o k response a status code equal to that given
func (o *VaultsGetTransfersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the vaults get transfers o k response
func (o *VaultsGetTransfersOK) Code() int {
	return 200
}

func (o *VaultsGetTransfersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/transfers][%d] vaultsGetTransfersOK %s", 200, payload)
}

func (o *VaultsGetTransfersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/transfers][%d] vaultsGetTransfersOK %s", 200, payload)
}

func (o *VaultsGetTransfersOK) GetPayload() *models.ResponsesVaultTransfersResp {
	return o.Payload
}

func (o *VaultsGetTransfersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesVaultTransfersResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVaultsGetTransfersBadRequest creates a VaultsGetTransfersBadRequest with default headers values
func NewVaultsGetTransfersBadRequest() *VaultsGetTransfersBadRequest {
	return &VaultsGetTransfersBadRequest{}
}

/*
VaultsGetTransfersBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VaultsGetTransfersBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this vaults get transfers bad request response has a 2xx status code
func (o *VaultsGetTransfersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this vaults get transfers bad request response has a 3xx status code
func (o *VaultsGetTransfersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get transfers bad request response has a 4xx status code
func (o *VaultsGetTransfersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this vaults get transfers bad request response has a 5xx status code
func (o *VaultsGetTransfersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get transfers bad request response a status code equal to that given
func (o *VaultsGetTransfersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the vaults get transfers bad request response
func (o *VaultsGetTransfersBadRequest) Code() int {
	return 400
}

func (o *VaultsGetTransfersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/transfers][%d] vaultsGetTransfersBadRequest %s", 400, payload)
}

func (o *VaultsGetTransfersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/transfers][%d] vaultsGetTransfersBadRequest %s", 400, payload)
}

func (o *VaultsGetTransfersBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *VaultsGetTransfersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
