// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// VaultsGetAccountSummaryReader is a Reader for the VaultsGetAccountSummary structure.
type VaultsGetAccountSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VaultsGetAccountSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVaultsGetAccountSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVaultsGetAccountSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /vaults/account-summary] vaults-get-account-summary", response, response.Code())
	}
}

// NewVaultsGetAccountSummaryOK creates a VaultsGetAccountSummaryOK with default headers values
func NewVaultsGetAccountSummaryOK() *VaultsGetAccountSummaryOK {
	return &VaultsGetAccountSummaryOK{}
}

/*
VaultsGetAccountSummaryOK describes a response with status code 200, with default header values.

OK
*/
type VaultsGetAccountSummaryOK struct {
	Payload *models.ResponsesGetVaultAccountSummariesResp
}

// IsSuccess returns true when this vaults get account summary o k response has a 2xx status code
func (o *VaultsGetAccountSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vaults get account summary o k response has a 3xx status code
func (o *VaultsGetAccountSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get account summary o k response has a 4xx status code
func (o *VaultsGetAccountSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vaults get account summary o k response has a 5xx status code
func (o *VaultsGetAccountSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get account summary o k response a status code equal to that given
func (o *VaultsGetAccountSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the vaults get account summary o k response
func (o *VaultsGetAccountSummaryOK) Code() int {
	return 200
}

func (o *VaultsGetAccountSummaryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/account-summary][%d] vaultsGetAccountSummaryOK %s", 200, payload)
}

func (o *VaultsGetAccountSummaryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/account-summary][%d] vaultsGetAccountSummaryOK %s", 200, payload)
}

func (o *VaultsGetAccountSummaryOK) GetPayload() *models.ResponsesGetVaultAccountSummariesResp {
	return o.Payload
}

func (o *VaultsGetAccountSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetVaultAccountSummariesResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVaultsGetAccountSummaryBadRequest creates a VaultsGetAccountSummaryBadRequest with default headers values
func NewVaultsGetAccountSummaryBadRequest() *VaultsGetAccountSummaryBadRequest {
	return &VaultsGetAccountSummaryBadRequest{}
}

/*
VaultsGetAccountSummaryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VaultsGetAccountSummaryBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this vaults get account summary bad request response has a 2xx status code
func (o *VaultsGetAccountSummaryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this vaults get account summary bad request response has a 3xx status code
func (o *VaultsGetAccountSummaryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get account summary bad request response has a 4xx status code
func (o *VaultsGetAccountSummaryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this vaults get account summary bad request response has a 5xx status code
func (o *VaultsGetAccountSummaryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get account summary bad request response a status code equal to that given
func (o *VaultsGetAccountSummaryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the vaults get account summary bad request response
func (o *VaultsGetAccountSummaryBadRequest) Code() int {
	return 400
}

func (o *VaultsGetAccountSummaryBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/account-summary][%d] vaultsGetAccountSummaryBadRequest %s", 400, payload)
}

func (o *VaultsGetAccountSummaryBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/account-summary][%d] vaultsGetAccountSummaryBadRequest %s", 400, payload)
}

func (o *VaultsGetAccountSummaryBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *VaultsGetAccountSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
