// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// VaultsGetPositionsReader is a Reader for the VaultsGetPositions structure.
type VaultsGetPositionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VaultsGetPositionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewVaultsGetPositionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewVaultsGetPositionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /vaults/positions] vaults-get-positions", response, response.Code())
	}
}

// NewVaultsGetPositionsOK creates a VaultsGetPositionsOK with default headers values
func NewVaultsGetPositionsOK() *VaultsGetPositionsOK {
	return &VaultsGetPositionsOK{}
}

/*
VaultsGetPositionsOK describes a response with status code 200, with default header values.

OK
*/
type VaultsGetPositionsOK struct {
	Payload *models.ResponsesVaultPositionsResp
}

// IsSuccess returns true when this vaults get positions o k response has a 2xx status code
func (o *VaultsGetPositionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this vaults get positions o k response has a 3xx status code
func (o *VaultsGetPositionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get positions o k response has a 4xx status code
func (o *VaultsGetPositionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this vaults get positions o k response has a 5xx status code
func (o *VaultsGetPositionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get positions o k response a status code equal to that given
func (o *VaultsGetPositionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the vaults get positions o k response
func (o *VaultsGetPositionsOK) Code() int {
	return 200
}

func (o *VaultsGetPositionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/positions][%d] vaultsGetPositionsOK %s", 200, payload)
}

func (o *VaultsGetPositionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/positions][%d] vaultsGetPositionsOK %s", 200, payload)
}

func (o *VaultsGetPositionsOK) GetPayload() *models.ResponsesVaultPositionsResp {
	return o.Payload
}

func (o *VaultsGetPositionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesVaultPositionsResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewVaultsGetPositionsBadRequest creates a VaultsGetPositionsBadRequest with default headers values
func NewVaultsGetPositionsBadRequest() *VaultsGetPositionsBadRequest {
	return &VaultsGetPositionsBadRequest{}
}

/*
VaultsGetPositionsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type VaultsGetPositionsBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this vaults get positions bad request response has a 2xx status code
func (o *VaultsGetPositionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this vaults get positions bad request response has a 3xx status code
func (o *VaultsGetPositionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this vaults get positions bad request response has a 4xx status code
func (o *VaultsGetPositionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this vaults get positions bad request response has a 5xx status code
func (o *VaultsGetPositionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this vaults get positions bad request response a status code equal to that given
func (o *VaultsGetPositionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the vaults get positions bad request response
func (o *VaultsGetPositionsBadRequest) Code() int {
	return 400
}

func (o *VaultsGetPositionsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/positions][%d] vaultsGetPositionsBadRequest %s", 400, payload)
}

func (o *VaultsGetPositionsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /vaults/positions][%d] vaultsGetPositionsBadRequest %s", 400, payload)
}

func (o *VaultsGetPositionsBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *VaultsGetPositionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
