// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// NewVaultsCreateParams creates a new VaultsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVaultsCreateParams() *VaultsCreateParams {
	return &VaultsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVaultsCreateParamsWithTimeout creates a new VaultsCreateParams object
// with the ability to set a timeout on a request.
func NewVaultsCreateParamsWithTimeout(timeout time.Duration) *VaultsCreateParams {
	return &VaultsCreateParams{
		timeout: timeout,
	}
}

// NewVaultsCreateParamsWithContext creates a new VaultsCreateParams object
// with the ability to set a context for a request.
func NewVaultsCreateParamsWithContext(ctx context.Context) *VaultsCreateParams {
	return &VaultsCreateParams{
		Context: ctx,
	}
}

// NewVaultsCreateParamsWithHTTPClient creates a new VaultsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewVaultsCreateParamsWithHTTPClient(client *http.Client) *VaultsCreateParams {
	return &VaultsCreateParams{
		HTTPClient: client,
	}
}

/*
VaultsCreateParams contains all the parameters to send to the API endpoint

	for the vaults create operation.

	Typically these are written to a http.Request.
*/
type VaultsCreateParams struct {

	/* PARADEXPARENTACCOUNT.

	   Onboarded by prdx:0xa123456789
	*/
	PARADEXPARENTACCOUNT string

	/* PARADEXSTARKNETACCOUNT.

	   Starknet address
	*/
	PARADEXSTARKNETACCOUNT string

	/* PARADEXSTARKNETACCOUNTDERIVATIONPATH.

	   Account derivation path - m/44'/9004'/0'/0/1
	*/
	PARADEXSTARKNETACCOUNTDERIVATIONPATH string

	/* PARADEXSTARKNETSIGNATURE.

	   Starknet signature
	*/
	PARADEXSTARKNETSIGNATURE string

	/* Params.

	   Vault parameters
	*/
	Params *models.RequestsCreateVault

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vaults create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsCreateParams) WithDefaults() *VaultsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vaults create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vaults create params
func (o *VaultsCreateParams) WithTimeout(timeout time.Duration) *VaultsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vaults create params
func (o *VaultsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vaults create params
func (o *VaultsCreateParams) WithContext(ctx context.Context) *VaultsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vaults create params
func (o *VaultsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vaults create params
func (o *VaultsCreateParams) WithHTTPClient(client *http.Client) *VaultsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vaults create params
func (o *VaultsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPARADEXPARENTACCOUNT adds the pARADEXPARENTACCOUNT to the vaults create params
func (o *VaultsCreateParams) WithPARADEXPARENTACCOUNT(pARADEXPARENTACCOUNT string) *VaultsCreateParams {
	o.SetPARADEXPARENTACCOUNT(pARADEXPARENTACCOUNT)
	return o
}

// SetPARADEXPARENTACCOUNT adds the pARADEXPARENTACCOUNT to the vaults create params
func (o *VaultsCreateParams) SetPARADEXPARENTACCOUNT(pARADEXPARENTACCOUNT string) {
	o.PARADEXPARENTACCOUNT = pARADEXPARENTACCOUNT
}

// WithPARADEXSTARKNETACCOUNT adds the pARADEXSTARKNETACCOUNT to the vaults create params
func (o *VaultsCreateParams) WithPARADEXSTARKNETACCOUNT(pARADEXSTARKNETACCOUNT string) *VaultsCreateParams {
	o.SetPARADEXSTARKNETACCOUNT(pARADEXSTARKNETACCOUNT)
	return o
}

// SetPARADEXSTARKNETACCOUNT adds the pARADEXSTARKNETACCOUNT to the vaults create params
func (o *VaultsCreateParams) SetPARADEXSTARKNETACCOUNT(pARADEXSTARKNETACCOUNT string) {
	o.PARADEXSTARKNETACCOUNT = pARADEXSTARKNETACCOUNT
}

// WithPARADEXSTARKNETACCOUNTDERIVATIONPATH adds the pARADEXSTARKNETACCOUNTDERIVATIONPATH to the vaults create params
func (o *VaultsCreateParams) WithPARADEXSTARKNETACCOUNTDERIVATIONPATH(pARADEXSTARKNETACCOUNTDERIVATIONPATH string) *VaultsCreateParams {
	o.SetPARADEXSTARKNETACCOUNTDERIVATIONPATH(pARADEXSTARKNETACCOUNTDERIVATIONPATH)
	return o
}

// SetPARADEXSTARKNETACCOUNTDERIVATIONPATH adds the pARADEXSTARKNETACCOUNTDERIVATIONPATH to the vaults create params
func (o *VaultsCreateParams) SetPARADEXSTARKNETACCOUNTDERIVATIONPATH(pARADEXSTARKNETACCOUNTDERIVATIONPATH string) {
	o.PARADEXSTARKNETACCOUNTDERIVATIONPATH = pARADEXSTARKNETACCOUNTDERIVATIONPATH
}

// WithPARADEXSTARKNETSIGNATURE adds the pARADEXSTARKNETSIGNATURE to the vaults create params
func (o *VaultsCreateParams) WithPARADEXSTARKNETSIGNATURE(pARADEXSTARKNETSIGNATURE string) *VaultsCreateParams {
	o.SetPARADEXSTARKNETSIGNATURE(pARADEXSTARKNETSIGNATURE)
	return o
}

// SetPARADEXSTARKNETSIGNATURE adds the pARADEXSTARKNETSIGNATURE to the vaults create params
func (o *VaultsCreateParams) SetPARADEXSTARKNETSIGNATURE(pARADEXSTARKNETSIGNATURE string) {
	o.PARADEXSTARKNETSIGNATURE = pARADEXSTARKNETSIGNATURE
}

// WithParams adds the params to the vaults create params
func (o *VaultsCreateParams) WithParams(params *models.RequestsCreateVault) *VaultsCreateParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the vaults create params
func (o *VaultsCreateParams) SetParams(params *models.RequestsCreateVault) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *VaultsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param PARADEX-PARENT-ACCOUNT
	if err := r.SetHeaderParam("PARADEX-PARENT-ACCOUNT", o.PARADEXPARENTACCOUNT); err != nil {
		return err
	}

	// header param PARADEX-STARKNET-ACCOUNT
	if err := r.SetHeaderParam("PARADEX-STARKNET-ACCOUNT", o.PARADEXSTARKNETACCOUNT); err != nil {
		return err
	}

	// header param PARADEX-STARKNET-ACCOUNT-DERIVATION-PATH
	if err := r.SetHeaderParam("PARADEX-STARKNET-ACCOUNT-DERIVATION-PATH", o.PARADEXSTARKNETACCOUNTDERIVATIONPATH); err != nil {
		return err
	}

	// header param PARADEX-STARKNET-SIGNATURE
	if err := r.SetHeaderParam("PARADEX-STARKNET-SIGNATURE", o.PARADEXSTARKNETSIGNATURE); err != nil {
		return err
	}
	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
