// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVaultsGetTransfersParams creates a new VaultsGetTransfersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVaultsGetTransfersParams() *VaultsGetTransfersParams {
	return &VaultsGetTransfersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVaultsGetTransfersParamsWithTimeout creates a new VaultsGetTransfersParams object
// with the ability to set a timeout on a request.
func NewVaultsGetTransfersParamsWithTimeout(timeout time.Duration) *VaultsGetTransfersParams {
	return &VaultsGetTransfersParams{
		timeout: timeout,
	}
}

// NewVaultsGetTransfersParamsWithContext creates a new VaultsGetTransfersParams object
// with the ability to set a context for a request.
func NewVaultsGetTransfersParamsWithContext(ctx context.Context) *VaultsGetTransfersParams {
	return &VaultsGetTransfersParams{
		Context: ctx,
	}
}

// NewVaultsGetTransfersParamsWithHTTPClient creates a new VaultsGetTransfersParams object
// with the ability to set a custom HTTPClient for a request.
func NewVaultsGetTransfersParamsWithHTTPClient(client *http.Client) *VaultsGetTransfersParams {
	return &VaultsGetTransfersParams{
		HTTPClient: client,
	}
}

/*
VaultsGetTransfersParams contains all the parameters to send to the API endpoint

	for the vaults get transfers operation.

	Typically these are written to a http.Request.
*/
type VaultsGetTransfersParams struct {

	/* Address.

	   Vault Address
	*/
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vaults get transfers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetTransfersParams) WithDefaults() *VaultsGetTransfersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vaults get transfers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetTransfersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vaults get transfers params
func (o *VaultsGetTransfersParams) WithTimeout(timeout time.Duration) *VaultsGetTransfersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vaults get transfers params
func (o *VaultsGetTransfersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vaults get transfers params
func (o *VaultsGetTransfersParams) WithContext(ctx context.Context) *VaultsGetTransfersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vaults get transfers params
func (o *VaultsGetTransfersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vaults get transfers params
func (o *VaultsGetTransfersParams) WithHTTPClient(client *http.Client) *VaultsGetTransfersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vaults get transfers params
func (o *VaultsGetTransfersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the vaults get transfers params
func (o *VaultsGetTransfersParams) WithAddress(address string) *VaultsGetTransfersParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the vaults get transfers params
func (o *VaultsGetTransfersParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *VaultsGetTransfersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param address
	qrAddress := o.Address
	qAddress := qrAddress
	if qAddress != "" {

		if err := r.SetQueryParam("address", qAddress); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
