// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVaultsGetConfigParams creates a new VaultsGetConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVaultsGetConfigParams() *VaultsGetConfigParams {
	return &VaultsGetConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVaultsGetConfigParamsWithTimeout creates a new VaultsGetConfigParams object
// with the ability to set a timeout on a request.
func NewVaultsGetConfigParamsWithTimeout(timeout time.Duration) *VaultsGetConfigParams {
	return &VaultsGetConfigParams{
		timeout: timeout,
	}
}

// NewVaultsGetConfigParamsWithContext creates a new VaultsGetConfigParams object
// with the ability to set a context for a request.
func NewVaultsGetConfigParamsWithContext(ctx context.Context) *VaultsGetConfigParams {
	return &VaultsGetConfigParams{
		Context: ctx,
	}
}

// NewVaultsGetConfigParamsWithHTTPClient creates a new VaultsGetConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewVaultsGetConfigParamsWithHTTPClient(client *http.Client) *VaultsGetConfigParams {
	return &VaultsGetConfigParams{
		HTTPClient: client,
	}
}

/*
VaultsGetConfigParams contains all the parameters to send to the API endpoint

	for the vaults get config operation.

	Typically these are written to a http.Request.
*/
type VaultsGetConfigParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vaults get config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetConfigParams) WithDefaults() *VaultsGetConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vaults get config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vaults get config params
func (o *VaultsGetConfigParams) WithTimeout(timeout time.Duration) *VaultsGetConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vaults get config params
func (o *VaultsGetConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vaults get config params
func (o *VaultsGetConfigParams) WithContext(ctx context.Context) *VaultsGetConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vaults get config params
func (o *VaultsGetConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vaults get config params
func (o *VaultsGetConfigParams) WithHTTPClient(client *http.Client) *VaultsGetConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vaults get config params
func (o *VaultsGetConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *VaultsGetConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
