// Code generated by go-swagger; DO NOT EDIT.

package vaults

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewVaultsGetParams creates a new VaultsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewVaultsGetParams() *VaultsGetParams {
	return &VaultsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewVaultsGetParamsWithTimeout creates a new VaultsGetParams object
// with the ability to set a timeout on a request.
func NewVaultsGetParamsWithTimeout(timeout time.Duration) *VaultsGetParams {
	return &VaultsGetParams{
		timeout: timeout,
	}
}

// NewVaultsGetParamsWithContext creates a new VaultsGetParams object
// with the ability to set a context for a request.
func NewVaultsGetParamsWithContext(ctx context.Context) *VaultsGetParams {
	return &VaultsGetParams{
		Context: ctx,
	}
}

// NewVaultsGetParamsWithHTTPClient creates a new VaultsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewVaultsGetParamsWithHTTPClient(client *http.Client) *VaultsGetParams {
	return &VaultsGetParams{
		HTTPClient: client,
	}
}

/*
VaultsGetParams contains all the parameters to send to the API endpoint

	for the vaults get operation.

	Typically these are written to a http.Request.
*/
type VaultsGetParams struct {

	/* Address.

	   Vault Address
	*/
	Address *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the vaults get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetParams) WithDefaults() *VaultsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the vaults get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *VaultsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the vaults get params
func (o *VaultsGetParams) WithTimeout(timeout time.Duration) *VaultsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the vaults get params
func (o *VaultsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the vaults get params
func (o *VaultsGetParams) WithContext(ctx context.Context) *VaultsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the vaults get params
func (o *VaultsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the vaults get params
func (o *VaultsGetParams) WithHTTPClient(client *http.Client) *VaultsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the vaults get params
func (o *VaultsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the vaults get params
func (o *VaultsGetParams) WithAddress(address *string) *VaultsGetParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the vaults get params
func (o *VaultsGetParams) SetAddress(address *string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *VaultsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Address != nil {

		// query param address
		var qrAddress string

		if o.Address != nil {
			qrAddress = *o.Address
		}
		qAddress := qrAddress
		if qAddress != "" {

			if err := r.SetQueryParam("address", qAddress); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
