// Code generated by go-swagger; DO NOT EDIT.

package markets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetOrderbookReader is a Reader for the GetOrderbook structure.
type GetOrderbookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrderbookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrderbookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrderbookBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /orderbook/{market}] get-orderbook", response, response.Code())
	}
}

// NewGetOrderbookOK creates a GetOrderbookOK with default headers values
func NewGetOrderbookOK() *GetOrderbookOK {
	return &GetOrderbookOK{}
}

/*
GetOrderbookOK describes a response with status code 200, with default header values.

OK
*/
type GetOrderbookOK struct {
	Payload *models.ResponsesAskBidArray
}

// IsSuccess returns true when this get orderbook o k response has a 2xx status code
func (o *GetOrderbookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get orderbook o k response has a 3xx status code
func (o *GetOrderbookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orderbook o k response has a 4xx status code
func (o *GetOrderbookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get orderbook o k response has a 5xx status code
func (o *GetOrderbookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get orderbook o k response a status code equal to that given
func (o *GetOrderbookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get orderbook o k response
func (o *GetOrderbookOK) Code() int {
	return 200
}

func (o *GetOrderbookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orderbook/{market}][%d] getOrderbookOK %s", 200, payload)
}

func (o *GetOrderbookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orderbook/{market}][%d] getOrderbookOK %s", 200, payload)
}

func (o *GetOrderbookOK) GetPayload() *models.ResponsesAskBidArray {
	return o.Payload
}

func (o *GetOrderbookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAskBidArray)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrderbookBadRequest creates a GetOrderbookBadRequest with default headers values
func NewGetOrderbookBadRequest() *GetOrderbookBadRequest {
	return &GetOrderbookBadRequest{}
}

/*
GetOrderbookBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetOrderbookBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get orderbook bad request response has a 2xx status code
func (o *GetOrderbookBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get orderbook bad request response has a 3xx status code
func (o *GetOrderbookBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get orderbook bad request response has a 4xx status code
func (o *GetOrderbookBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get orderbook bad request response has a 5xx status code
func (o *GetOrderbookBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get orderbook bad request response a status code equal to that given
func (o *GetOrderbookBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get orderbook bad request response
func (o *GetOrderbookBadRequest) Code() int {
	return 400
}

func (o *GetOrderbookBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orderbook/{market}][%d] getOrderbookBadRequest %s", 400, payload)
}

func (o *GetOrderbookBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /orderbook/{market}][%d] getOrderbookBadRequest %s", 400, payload)
}

func (o *GetOrderbookBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetOrderbookBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
