// Code generated by go-swagger; DO NOT EDIT.

package markets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetMarketsSummaryReader is a Reader for the GetMarketsSummary structure.
type GetMarketsSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMarketsSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMarketsSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMarketsSummaryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /markets/summary] get-markets-summary", response, response.Code())
	}
}

// NewGetMarketsSummaryOK creates a GetMarketsSummaryOK with default headers values
func NewGetMarketsSummaryOK() *GetMarketsSummaryOK {
	return &GetMarketsSummaryOK{}
}

/*
GetMarketsSummaryOK describes a response with status code 200, with default header values.

OK
*/
type GetMarketsSummaryOK struct {
	Payload *models.ResponsesGetMarketSummary
}

// IsSuccess returns true when this get markets summary o k response has a 2xx status code
func (o *GetMarketsSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get markets summary o k response has a 3xx status code
func (o *GetMarketsSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get markets summary o k response has a 4xx status code
func (o *GetMarketsSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get markets summary o k response has a 5xx status code
func (o *GetMarketsSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get markets summary o k response a status code equal to that given
func (o *GetMarketsSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get markets summary o k response
func (o *GetMarketsSummaryOK) Code() int {
	return 200
}

func (o *GetMarketsSummaryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/summary][%d] getMarketsSummaryOK %s", 200, payload)
}

func (o *GetMarketsSummaryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/summary][%d] getMarketsSummaryOK %s", 200, payload)
}

func (o *GetMarketsSummaryOK) GetPayload() *models.ResponsesGetMarketSummary {
	return o.Payload
}

func (o *GetMarketsSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetMarketSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMarketsSummaryBadRequest creates a GetMarketsSummaryBadRequest with default headers values
func NewGetMarketsSummaryBadRequest() *GetMarketsSummaryBadRequest {
	return &GetMarketsSummaryBadRequest{}
}

/*
GetMarketsSummaryBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetMarketsSummaryBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get markets summary bad request response has a 2xx status code
func (o *GetMarketsSummaryBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get markets summary bad request response has a 3xx status code
func (o *GetMarketsSummaryBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get markets summary bad request response has a 4xx status code
func (o *GetMarketsSummaryBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get markets summary bad request response has a 5xx status code
func (o *GetMarketsSummaryBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get markets summary bad request response a status code equal to that given
func (o *GetMarketsSummaryBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get markets summary bad request response
func (o *GetMarketsSummaryBadRequest) Code() int {
	return 400
}

func (o *GetMarketsSummaryBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/summary][%d] getMarketsSummaryBadRequest %s", 400, payload)
}

func (o *GetMarketsSummaryBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/summary][%d] getMarketsSummaryBadRequest %s", 400, payload)
}

func (o *GetMarketsSummaryBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetMarketsSummaryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
