// Code generated by go-swagger; DO NOT EDIT.

package markets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// MarketsKlinesReader is a Reader for the MarketsKlines structure.
type MarketsKlinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MarketsKlinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 400:
		result := NewMarketsKlinesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /markets/klines] markets-klines", response, response.Code())
	}
}

// NewMarketsKlinesBadRequest creates a MarketsKlinesBadRequest with default headers values
func NewMarketsKlinesBadRequest() *MarketsKlinesBadRequest {
	return &MarketsKlinesBadRequest{}
}

/*
MarketsKlinesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type MarketsKlinesBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this markets klines bad request response has a 2xx status code
func (o *MarketsKlinesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this markets klines bad request response has a 3xx status code
func (o *MarketsKlinesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this markets klines bad request response has a 4xx status code
func (o *MarketsKlinesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this markets klines bad request response has a 5xx status code
func (o *MarketsKlinesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this markets klines bad request response a status code equal to that given
func (o *MarketsKlinesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the markets klines bad request response
func (o *MarketsKlinesBadRequest) Code() int {
	return 400
}

func (o *MarketsKlinesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/klines][%d] marketsKlinesBadRequest %s", 400, payload)
}

func (o *MarketsKlinesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /markets/klines][%d] marketsKlinesBadRequest %s", 400, payload)
}

func (o *MarketsKlinesBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *MarketsKlinesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
