// Code generated by go-swagger; DO NOT EDIT.

package insurance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInsuranceFundParams creates a new GetInsuranceFundParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInsuranceFundParams() *GetInsuranceFundParams {
	return &GetInsuranceFundParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInsuranceFundParamsWithTimeout creates a new GetInsuranceFundParams object
// with the ability to set a timeout on a request.
func NewGetInsuranceFundParamsWithTimeout(timeout time.Duration) *GetInsuranceFundParams {
	return &GetInsuranceFundParams{
		timeout: timeout,
	}
}

// NewGetInsuranceFundParamsWithContext creates a new GetInsuranceFundParams object
// with the ability to set a context for a request.
func NewGetInsuranceFundParamsWithContext(ctx context.Context) *GetInsuranceFundParams {
	return &GetInsuranceFundParams{
		Context: ctx,
	}
}

// NewGetInsuranceFundParamsWithHTTPClient creates a new GetInsuranceFundParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInsuranceFundParamsWithHTTPClient(client *http.Client) *GetInsuranceFundParams {
	return &GetInsuranceFundParams{
		HTTPClient: client,
	}
}

/*
GetInsuranceFundParams contains all the parameters to send to the API endpoint

	for the get insurance fund operation.

	Typically these are written to a http.Request.
*/
type GetInsuranceFundParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get insurance fund params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsuranceFundParams) WithDefaults() *GetInsuranceFundParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get insurance fund params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsuranceFundParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get insurance fund params
func (o *GetInsuranceFundParams) WithTimeout(timeout time.Duration) *GetInsuranceFundParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get insurance fund params
func (o *GetInsuranceFundParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get insurance fund params
func (o *GetInsuranceFundParams) WithContext(ctx context.Context) *GetInsuranceFundParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get insurance fund params
func (o *GetInsuranceFundParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get insurance fund params
func (o *GetInsuranceFundParams) WithHTTPClient(client *http.Client) *GetInsuranceFundParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get insurance fund params
func (o *GetInsuranceFundParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetInsuranceFundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
