// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountProfileParams creates a new GetAccountProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountProfileParams() *GetAccountProfileParams {
	return &GetAccountProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountProfileParamsWithTimeout creates a new GetAccountProfileParams object
// with the ability to set a timeout on a request.
func NewGetAccountProfileParamsWithTimeout(timeout time.Duration) *GetAccountProfileParams {
	return &GetAccountProfileParams{
		timeout: timeout,
	}
}

// NewGetAccountProfileParamsWithContext creates a new GetAccountProfileParams object
// with the ability to set a context for a request.
func NewGetAccountProfileParamsWithContext(ctx context.Context) *GetAccountProfileParams {
	return &GetAccountProfileParams{
		Context: ctx,
	}
}

// NewGetAccountProfileParamsWithHTTPClient creates a new GetAccountProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountProfileParamsWithHTTPClient(client *http.Client) *GetAccountProfileParams {
	return &GetAccountProfileParams{
		HTTPClient: client,
	}
}

/*
GetAccountProfileParams contains all the parameters to send to the API endpoint

	for the get account profile operation.

	Typically these are written to a http.Request.
*/
type GetAccountProfileParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get account profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountProfileParams) WithDefaults() *GetAccountProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get account profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get account profile params
func (o *GetAccountProfileParams) WithTimeout(timeout time.Duration) *GetAccountProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account profile params
func (o *GetAccountProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account profile params
func (o *GetAccountProfileParams) WithContext(ctx context.Context) *GetAccountProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account profile params
func (o *GetAccountProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account profile params
func (o *GetAccountProfileParams) WithHTTPClient(client *http.Client) *GetAccountProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account profile params
func (o *GetAccountProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
