// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountHistoryParams creates a new GetAccountHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountHistoryParams() *GetAccountHistoryParams {
	return &GetAccountHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountHistoryParamsWithTimeout creates a new GetAccountHistoryParams object
// with the ability to set a timeout on a request.
func NewGetAccountHistoryParamsWithTimeout(timeout time.Duration) *GetAccountHistoryParams {
	return &GetAccountHistoryParams{
		timeout: timeout,
	}
}

// NewGetAccountHistoryParamsWithContext creates a new GetAccountHistoryParams object
// with the ability to set a context for a request.
func NewGetAccountHistoryParamsWithContext(ctx context.Context) *GetAccountHistoryParams {
	return &GetAccountHistoryParams{
		Context: ctx,
	}
}

// NewGetAccountHistoryParamsWithHTTPClient creates a new GetAccountHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountHistoryParamsWithHTTPClient(client *http.Client) *GetAccountHistoryParams {
	return &GetAccountHistoryParams{
		HTTPClient: client,
	}
}

/*
GetAccountHistoryParams contains all the parameters to send to the API endpoint

	for the get account history operation.

	Typically these are written to a http.Request.
*/
type GetAccountHistoryParams struct {

	/* Type.

	   Type of data
	*/
	Type string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get account history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountHistoryParams) WithDefaults() *GetAccountHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get account history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get account history params
func (o *GetAccountHistoryParams) WithTimeout(timeout time.Duration) *GetAccountHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account history params
func (o *GetAccountHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account history params
func (o *GetAccountHistoryParams) WithContext(ctx context.Context) *GetAccountHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account history params
func (o *GetAccountHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account history params
func (o *GetAccountHistoryParams) WithHTTPClient(client *http.Client) *GetAccountHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account history params
func (o *GetAccountHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the get account history params
func (o *GetAccountHistoryParams) WithType(typeVar string) *GetAccountHistoryParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get account history params
func (o *GetAccountHistoryParams) SetType(typeVar string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param type
	qrType := o.Type
	qType := qrType
	if qType != "" {

		if err := r.SetQueryParam("type", qType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
