// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// GetAccountProfileReader is a Reader for the GetAccountProfile structure.
type GetAccountProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAccountProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAccountProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /account/profile] get-account-profile", response, response.Code())
	}
}

// NewGetAccountProfileOK creates a GetAccountProfileOK with default headers values
func NewGetAccountProfileOK() *GetAccountProfileOK {
	return &GetAccountProfileOK{}
}

/*
GetAccountProfileOK describes a response with status code 200, with default header values.

OK
*/
type GetAccountProfileOK struct {
	Payload *models.ResponsesAccountProfileResp
}

// IsSuccess returns true when this get account profile o k response has a 2xx status code
func (o *GetAccountProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get account profile o k response has a 3xx status code
func (o *GetAccountProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account profile o k response has a 4xx status code
func (o *GetAccountProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get account profile o k response has a 5xx status code
func (o *GetAccountProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get account profile o k response a status code equal to that given
func (o *GetAccountProfileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get account profile o k response
func (o *GetAccountProfileOK) Code() int {
	return 200
}

func (o *GetAccountProfileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileOK %s", 200, payload)
}

func (o *GetAccountProfileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileOK %s", 200, payload)
}

func (o *GetAccountProfileOK) GetPayload() *models.ResponsesAccountProfileResp {
	return o.Payload
}

func (o *GetAccountProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAccountProfileResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountProfileBadRequest creates a GetAccountProfileBadRequest with default headers values
func NewGetAccountProfileBadRequest() *GetAccountProfileBadRequest {
	return &GetAccountProfileBadRequest{}
}

/*
GetAccountProfileBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAccountProfileBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get account profile bad request response has a 2xx status code
func (o *GetAccountProfileBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get account profile bad request response has a 3xx status code
func (o *GetAccountProfileBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account profile bad request response has a 4xx status code
func (o *GetAccountProfileBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get account profile bad request response has a 5xx status code
func (o *GetAccountProfileBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get account profile bad request response a status code equal to that given
func (o *GetAccountProfileBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get account profile bad request response
func (o *GetAccountProfileBadRequest) Code() int {
	return 400
}

func (o *GetAccountProfileBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileBadRequest %s", 400, payload)
}

func (o *GetAccountProfileBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileBadRequest %s", 400, payload)
}

func (o *GetAccountProfileBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetAccountProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountProfileUnauthorized creates a GetAccountProfileUnauthorized with default headers values
func NewGetAccountProfileUnauthorized() *GetAccountProfileUnauthorized {
	return &GetAccountProfileUnauthorized{}
}

/*
GetAccountProfileUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAccountProfileUnauthorized struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this get account profile unauthorized response has a 2xx status code
func (o *GetAccountProfileUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get account profile unauthorized response has a 3xx status code
func (o *GetAccountProfileUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get account profile unauthorized response has a 4xx status code
func (o *GetAccountProfileUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get account profile unauthorized response has a 5xx status code
func (o *GetAccountProfileUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get account profile unauthorized response a status code equal to that given
func (o *GetAccountProfileUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get account profile unauthorized response
func (o *GetAccountProfileUnauthorized) Code() int {
	return 401
}

func (o *GetAccountProfileUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileUnauthorized %s", 401, payload)
}

func (o *GetAccountProfileUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /account/profile][%d] getAccountProfileUnauthorized %s", 401, payload)
}

func (o *GetAccountProfileUnauthorized) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *GetAccountProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
