// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountMarginParams creates a new GetAccountMarginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountMarginParams() *GetAccountMarginParams {
	return &GetAccountMarginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountMarginParamsWithTimeout creates a new GetAccountMarginParams object
// with the ability to set a timeout on a request.
func NewGetAccountMarginParamsWithTimeout(timeout time.Duration) *GetAccountMarginParams {
	return &GetAccountMarginParams{
		timeout: timeout,
	}
}

// NewGetAccountMarginParamsWithContext creates a new GetAccountMarginParams object
// with the ability to set a context for a request.
func NewGetAccountMarginParamsWithContext(ctx context.Context) *GetAccountMarginParams {
	return &GetAccountMarginParams{
		Context: ctx,
	}
}

// NewGetAccountMarginParamsWithHTTPClient creates a new GetAccountMarginParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountMarginParamsWithHTTPClient(client *http.Client) *GetAccountMarginParams {
	return &GetAccountMarginParams{
		HTTPClient: client,
	}
}

/*
GetAccountMarginParams contains all the parameters to send to the API endpoint

	for the get account margin operation.

	Typically these are written to a http.Request.
*/
type GetAccountMarginParams struct {

	/* Market.

	   Market Name - example: BTC-USD-PERP
	*/
	Market string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get account margin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountMarginParams) WithDefaults() *GetAccountMarginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get account margin params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountMarginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get account margin params
func (o *GetAccountMarginParams) WithTimeout(timeout time.Duration) *GetAccountMarginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account margin params
func (o *GetAccountMarginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account margin params
func (o *GetAccountMarginParams) WithContext(ctx context.Context) *GetAccountMarginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account margin params
func (o *GetAccountMarginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account margin params
func (o *GetAccountMarginParams) WithHTTPClient(client *http.Client) *GetAccountMarginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account margin params
func (o *GetAccountMarginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMarket adds the market to the get account margin params
func (o *GetAccountMarginParams) WithMarket(market string) *GetAccountMarginParams {
	o.SetMarket(market)
	return o
}

// SetMarket adds the market to the get account margin params
func (o *GetAccountMarginParams) SetMarket(market string) {
	o.Market = market
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountMarginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param market
	qrMarket := o.Market
	qMarket := qrMarket
	if qMarket != "" {

		if err := r.SetQueryParam("market", qMarket); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
