// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountsInfoParams creates a new GetAccountsInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAccountsInfoParams() *GetAccountsInfoParams {
	return &GetAccountsInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountsInfoParamsWithTimeout creates a new GetAccountsInfoParams object
// with the ability to set a timeout on a request.
func NewGetAccountsInfoParamsWithTimeout(timeout time.Duration) *GetAccountsInfoParams {
	return &GetAccountsInfoParams{
		timeout: timeout,
	}
}

// NewGetAccountsInfoParamsWithContext creates a new GetAccountsInfoParams object
// with the ability to set a context for a request.
func NewGetAccountsInfoParamsWithContext(ctx context.Context) *GetAccountsInfoParams {
	return &GetAccountsInfoParams{
		Context: ctx,
	}
}

// NewGetAccountsInfoParamsWithHTTPClient creates a new GetAccountsInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAccountsInfoParamsWithHTTPClient(client *http.Client) *GetAccountsInfoParams {
	return &GetAccountsInfoParams{
		HTTPClient: client,
	}
}

/*
GetAccountsInfoParams contains all the parameters to send to the API endpoint

	for the get accounts info operation.

	Typically these are written to a http.Request.
*/
type GetAccountsInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get accounts info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountsInfoParams) WithDefaults() *GetAccountsInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get accounts info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAccountsInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get accounts info params
func (o *GetAccountsInfoParams) WithTimeout(timeout time.Duration) *GetAccountsInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get accounts info params
func (o *GetAccountsInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get accounts info params
func (o *GetAccountsInfoParams) WithContext(ctx context.Context) *GetAccountsInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get accounts info params
func (o *GetAccountsInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get accounts info params
func (o *GetAccountsInfoParams) WithHTTPClient(client *http.Client) *GetAccountsInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get accounts info params
func (o *GetAccountsInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountsInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
