// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFillsParams creates a new GetFillsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetFillsParams() *GetFillsParams {
	return &GetFillsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetFillsParamsWithTimeout creates a new GetFillsParams object
// with the ability to set a timeout on a request.
func NewGetFillsParamsWithTimeout(timeout time.Duration) *GetFillsParams {
	return &GetFillsParams{
		timeout: timeout,
	}
}

// NewGetFillsParamsWithContext creates a new GetFillsParams object
// with the ability to set a context for a request.
func NewGetFillsParamsWithContext(ctx context.Context) *GetFillsParams {
	return &GetFillsParams{
		Context: ctx,
	}
}

// NewGetFillsParamsWithHTTPClient creates a new GetFillsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetFillsParamsWithHTTPClient(client *http.Client) *GetFillsParams {
	return &GetFillsParams{
		HTTPClient: client,
	}
}

/*
GetFillsParams contains all the parameters to send to the API endpoint

	for the get fills operation.

	Typically these are written to a http.Request.
*/
type GetFillsParams struct {

	/* Cursor.

	   Returns the ‘next’ paginated page.
	*/
	Cursor *string

	/* EndAt.

	   End Time (unix time millisecond)
	*/
	EndAt *int64

	// Market.
	Market *string

	/* PageSize.

	   Limit the number of responses in the page

	   Default: 100
	*/
	PageSize *int64

	/* StartAt.

	   Start Time (unix time millisecond)
	*/
	StartAt *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get fills params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFillsParams) WithDefaults() *GetFillsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get fills params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetFillsParams) SetDefaults() {
	var (
		pageSizeDefault = int64(100)
	)

	val := GetFillsParams{
		PageSize: &pageSizeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get fills params
func (o *GetFillsParams) WithTimeout(timeout time.Duration) *GetFillsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fills params
func (o *GetFillsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fills params
func (o *GetFillsParams) WithContext(ctx context.Context) *GetFillsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fills params
func (o *GetFillsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fills params
func (o *GetFillsParams) WithHTTPClient(client *http.Client) *GetFillsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fills params
func (o *GetFillsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the get fills params
func (o *GetFillsParams) WithCursor(cursor *string) *GetFillsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the get fills params
func (o *GetFillsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithEndAt adds the endAt to the get fills params
func (o *GetFillsParams) WithEndAt(endAt *int64) *GetFillsParams {
	o.SetEndAt(endAt)
	return o
}

// SetEndAt adds the endAt to the get fills params
func (o *GetFillsParams) SetEndAt(endAt *int64) {
	o.EndAt = endAt
}

// WithMarket adds the market to the get fills params
func (o *GetFillsParams) WithMarket(market *string) *GetFillsParams {
	o.SetMarket(market)
	return o
}

// SetMarket adds the market to the get fills params
func (o *GetFillsParams) SetMarket(market *string) {
	o.Market = market
}

// WithPageSize adds the pageSize to the get fills params
func (o *GetFillsParams) WithPageSize(pageSize *int64) *GetFillsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get fills params
func (o *GetFillsParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithStartAt adds the startAt to the get fills params
func (o *GetFillsParams) WithStartAt(startAt *int64) *GetFillsParams {
	o.SetStartAt(startAt)
	return o
}

// SetStartAt adds the startAt to the get fills params
func (o *GetFillsParams) SetStartAt(startAt *int64) {
	o.StartAt = startAt
}

// WriteToRequest writes these params to a swagger request
func (o *GetFillsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.EndAt != nil {

		// query param end_at
		var qrEndAt int64

		if o.EndAt != nil {
			qrEndAt = *o.EndAt
		}
		qEndAt := swag.FormatInt64(qrEndAt)
		if qEndAt != "" {

			if err := r.SetQueryParam("end_at", qEndAt); err != nil {
				return err
			}
		}
	}

	if o.Market != nil {

		// query param market
		var qrMarket string

		if o.Market != nil {
			qrMarket = *o.Market
		}
		qMarket := qrMarket
		if qMarket != "" {

			if err := r.SetQueryParam("market", qMarket); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.StartAt != nil {

		// query param start_at
		var qrStartAt int64

		if o.StartAt != nil {
			qrStartAt = *o.StartAt
		}
		qStartAt := swag.FormatInt64(qrStartAt)
		if qStartAt != "" {

			if err := r.SetQueryParam("start_at", qStartAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
