// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateAccountProfileReferralCodeParams creates a new UpdateAccountProfileReferralCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAccountProfileReferralCodeParams() *UpdateAccountProfileReferralCodeParams {
	return &UpdateAccountProfileReferralCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccountProfileReferralCodeParamsWithTimeout creates a new UpdateAccountProfileReferralCodeParams object
// with the ability to set a timeout on a request.
func NewUpdateAccountProfileReferralCodeParamsWithTimeout(timeout time.Duration) *UpdateAccountProfileReferralCodeParams {
	return &UpdateAccountProfileReferralCodeParams{
		timeout: timeout,
	}
}

// NewUpdateAccountProfileReferralCodeParamsWithContext creates a new UpdateAccountProfileReferralCodeParams object
// with the ability to set a context for a request.
func NewUpdateAccountProfileReferralCodeParamsWithContext(ctx context.Context) *UpdateAccountProfileReferralCodeParams {
	return &UpdateAccountProfileReferralCodeParams{
		Context: ctx,
	}
}

// NewUpdateAccountProfileReferralCodeParamsWithHTTPClient creates a new UpdateAccountProfileReferralCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAccountProfileReferralCodeParamsWithHTTPClient(client *http.Client) *UpdateAccountProfileReferralCodeParams {
	return &UpdateAccountProfileReferralCodeParams{
		HTTPClient: client,
	}
}

/*
UpdateAccountProfileReferralCodeParams contains all the parameters to send to the API endpoint

	for the update account profile referral code operation.

	Typically these are written to a http.Request.
*/
type UpdateAccountProfileReferralCodeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update account profile referral code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountProfileReferralCodeParams) WithDefaults() *UpdateAccountProfileReferralCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update account profile referral code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountProfileReferralCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) WithTimeout(timeout time.Duration) *UpdateAccountProfileReferralCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) WithContext(ctx context.Context) *UpdateAccountProfileReferralCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) WithHTTPClient(client *http.Client) *UpdateAccountProfileReferralCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update account profile referral code params
func (o *UpdateAccountProfileReferralCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccountProfileReferralCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
