// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateAccountProfileUsernameParams creates a new UpdateAccountProfileUsernameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAccountProfileUsernameParams() *UpdateAccountProfileUsernameParams {
	return &UpdateAccountProfileUsernameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccountProfileUsernameParamsWithTimeout creates a new UpdateAccountProfileUsernameParams object
// with the ability to set a timeout on a request.
func NewUpdateAccountProfileUsernameParamsWithTimeout(timeout time.Duration) *UpdateAccountProfileUsernameParams {
	return &UpdateAccountProfileUsernameParams{
		timeout: timeout,
	}
}

// NewUpdateAccountProfileUsernameParamsWithContext creates a new UpdateAccountProfileUsernameParams object
// with the ability to set a context for a request.
func NewUpdateAccountProfileUsernameParamsWithContext(ctx context.Context) *UpdateAccountProfileUsernameParams {
	return &UpdateAccountProfileUsernameParams{
		Context: ctx,
	}
}

// NewUpdateAccountProfileUsernameParamsWithHTTPClient creates a new UpdateAccountProfileUsernameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAccountProfileUsernameParamsWithHTTPClient(client *http.Client) *UpdateAccountProfileUsernameParams {
	return &UpdateAccountProfileUsernameParams{
		HTTPClient: client,
	}
}

/*
UpdateAccountProfileUsernameParams contains all the parameters to send to the API endpoint

	for the update account profile username operation.

	Typically these are written to a http.Request.
*/
type UpdateAccountProfileUsernameParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update account profile username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountProfileUsernameParams) WithDefaults() *UpdateAccountProfileUsernameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update account profile username params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountProfileUsernameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) WithTimeout(timeout time.Duration) *UpdateAccountProfileUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) WithContext(ctx context.Context) *UpdateAccountProfileUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) WithHTTPClient(client *http.Client) *UpdateAccountProfileUsernameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update account profile username params
func (o *UpdateAccountProfileUsernameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccountProfileUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
