// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// NewUpdateAccountMaxSlippageParams creates a new UpdateAccountMaxSlippageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateAccountMaxSlippageParams() *UpdateAccountMaxSlippageParams {
	return &UpdateAccountMaxSlippageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccountMaxSlippageParamsWithTimeout creates a new UpdateAccountMaxSlippageParams object
// with the ability to set a timeout on a request.
func NewUpdateAccountMaxSlippageParamsWithTimeout(timeout time.Duration) *UpdateAccountMaxSlippageParams {
	return &UpdateAccountMaxSlippageParams{
		timeout: timeout,
	}
}

// NewUpdateAccountMaxSlippageParamsWithContext creates a new UpdateAccountMaxSlippageParams object
// with the ability to set a context for a request.
func NewUpdateAccountMaxSlippageParamsWithContext(ctx context.Context) *UpdateAccountMaxSlippageParams {
	return &UpdateAccountMaxSlippageParams{
		Context: ctx,
	}
}

// NewUpdateAccountMaxSlippageParamsWithHTTPClient creates a new UpdateAccountMaxSlippageParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateAccountMaxSlippageParamsWithHTTPClient(client *http.Client) *UpdateAccountMaxSlippageParams {
	return &UpdateAccountMaxSlippageParams{
		HTTPClient: client,
	}
}

/*
UpdateAccountMaxSlippageParams contains all the parameters to send to the API endpoint

	for the update account max slippage operation.

	Typically these are written to a http.Request.
*/
type UpdateAccountMaxSlippageParams struct {

	/* Request.

	   Update max slippage request
	*/
	Request *models.RequestsUpdateAccountMaxSlippageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update account max slippage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountMaxSlippageParams) WithDefaults() *UpdateAccountMaxSlippageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update account max slippage params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateAccountMaxSlippageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) WithTimeout(timeout time.Duration) *UpdateAccountMaxSlippageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) WithContext(ctx context.Context) *UpdateAccountMaxSlippageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) WithHTTPClient(client *http.Client) *UpdateAccountMaxSlippageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) WithRequest(request *models.RequestsUpdateAccountMaxSlippageRequest) *UpdateAccountMaxSlippageParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the update account max slippage params
func (o *UpdateAccountMaxSlippageParams) SetRequest(request *models.RequestsUpdateAccountMaxSlippageRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccountMaxSlippageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
