// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// UpsertAccountMarginReader is a Reader for the UpsertAccountMargin structure.
type UpsertAccountMarginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpsertAccountMarginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpsertAccountMarginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpsertAccountMarginBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /account/margin/{market}] upsert-account-margin", response, response.Code())
	}
}

// NewUpsertAccountMarginOK creates a UpsertAccountMarginOK with default headers values
func NewUpsertAccountMarginOK() *UpsertAccountMarginOK {
	return &UpsertAccountMarginOK{}
}

/*
UpsertAccountMarginOK describes a response with status code 200, with default header values.

OK
*/
type UpsertAccountMarginOK struct {
	Payload *models.MessageAccountMarginConfig
}

// IsSuccess returns true when this upsert account margin o k response has a 2xx status code
func (o *UpsertAccountMarginOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upsert account margin o k response has a 3xx status code
func (o *UpsertAccountMarginOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upsert account margin o k response has a 4xx status code
func (o *UpsertAccountMarginOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upsert account margin o k response has a 5xx status code
func (o *UpsertAccountMarginOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upsert account margin o k response a status code equal to that given
func (o *UpsertAccountMarginOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upsert account margin o k response
func (o *UpsertAccountMarginOK) Code() int {
	return 200
}

func (o *UpsertAccountMarginOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /account/margin/{market}][%d] upsertAccountMarginOK %s", 200, payload)
}

func (o *UpsertAccountMarginOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /account/margin/{market}][%d] upsertAccountMarginOK %s", 200, payload)
}

func (o *UpsertAccountMarginOK) GetPayload() *models.MessageAccountMarginConfig {
	return o.Payload
}

func (o *UpsertAccountMarginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MessageAccountMarginConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpsertAccountMarginBadRequest creates a UpsertAccountMarginBadRequest with default headers values
func NewUpsertAccountMarginBadRequest() *UpsertAccountMarginBadRequest {
	return &UpsertAccountMarginBadRequest{}
}

/*
UpsertAccountMarginBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpsertAccountMarginBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this upsert account margin bad request response has a 2xx status code
func (o *UpsertAccountMarginBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this upsert account margin bad request response has a 3xx status code
func (o *UpsertAccountMarginBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upsert account margin bad request response has a 4xx status code
func (o *UpsertAccountMarginBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this upsert account margin bad request response has a 5xx status code
func (o *UpsertAccountMarginBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this upsert account margin bad request response a status code equal to that given
func (o *UpsertAccountMarginBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the upsert account margin bad request response
func (o *UpsertAccountMarginBadRequest) Code() int {
	return 400
}

func (o *UpsertAccountMarginBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /account/margin/{market}][%d] upsertAccountMarginBadRequest %s", 400, payload)
}

func (o *UpsertAccountMarginBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /account/margin/{market}][%d] upsertAccountMarginBadRequest %s", 400, payload)
}

func (o *UpsertAccountMarginBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *UpsertAccountMarginBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
