// Code generated by go-swagger; DO NOT EDIT.

package trades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// TradesReader is a Reader for the Trades structure.
type TradesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TradesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTradesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewTradesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /trades] trades", response, response.Code())
	}
}

// NewTradesOK creates a TradesOK with default headers values
func NewTradesOK() *TradesOK {
	return &TradesOK{}
}

/*
TradesOK describes a response with status code 200, with default header values.

OK
*/
type TradesOK struct {
	Payload *models.ResponsesGetTradesResp
}

// IsSuccess returns true when this trades o k response has a 2xx status code
func (o *TradesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this trades o k response has a 3xx status code
func (o *TradesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this trades o k response has a 4xx status code
func (o *TradesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this trades o k response has a 5xx status code
func (o *TradesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this trades o k response a status code equal to that given
func (o *TradesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the trades o k response
func (o *TradesOK) Code() int {
	return 200
}

func (o *TradesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trades][%d] tradesOK %s", 200, payload)
}

func (o *TradesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trades][%d] tradesOK %s", 200, payload)
}

func (o *TradesOK) GetPayload() *models.ResponsesGetTradesResp {
	return o.Payload
}

func (o *TradesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesGetTradesResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTradesBadRequest creates a TradesBadRequest with default headers values
func NewTradesBadRequest() *TradesBadRequest {
	return &TradesBadRequest{}
}

/*
TradesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TradesBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this trades bad request response has a 2xx status code
func (o *TradesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this trades bad request response has a 3xx status code
func (o *TradesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this trades bad request response has a 4xx status code
func (o *TradesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this trades bad request response has a 5xx status code
func (o *TradesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this trades bad request response a status code equal to that given
func (o *TradesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the trades bad request response
func (o *TradesBadRequest) Code() int {
	return 400
}

func (o *TradesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trades][%d] tradesBadRequest %s", 400, payload)
}

func (o *TradesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /trades][%d] tradesBadRequest %s", 400, payload)
}

func (o *TradesBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *TradesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
