// Code generated by go-swagger; DO NOT EDIT.

package trades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTradesParams creates a new TradesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTradesParams() *TradesParams {
	return &TradesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTradesParamsWithTimeout creates a new TradesParams object
// with the ability to set a timeout on a request.
func NewTradesParamsWithTimeout(timeout time.Duration) *TradesParams {
	return &TradesParams{
		timeout: timeout,
	}
}

// NewTradesParamsWithContext creates a new TradesParams object
// with the ability to set a context for a request.
func NewTradesParamsWithContext(ctx context.Context) *TradesParams {
	return &TradesParams{
		Context: ctx,
	}
}

// NewTradesParamsWithHTTPClient creates a new TradesParams object
// with the ability to set a custom HTTPClient for a request.
func NewTradesParamsWithHTTPClient(client *http.Client) *TradesParams {
	return &TradesParams{
		HTTPClient: client,
	}
}

/*
TradesParams contains all the parameters to send to the API endpoint

	for the trades operation.

	Typically these are written to a http.Request.
*/
type TradesParams struct {

	/* Cursor.

	   Returns the ‘next’ paginated page.
	*/
	Cursor *string

	/* EndAt.

	   End Time (unix time millisecond)
	*/
	EndAt *int64

	/* Market.

	   Market name
	*/
	Market string

	/* PageSize.

	   Limit the number of responses in the page

	   Default: 100
	*/
	PageSize *int64

	/* StartAt.

	   Start Time (unix time millisecond)
	*/
	StartAt *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the trades params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TradesParams) WithDefaults() *TradesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the trades params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TradesParams) SetDefaults() {
	var (
		pageSizeDefault = int64(100)
	)

	val := TradesParams{
		PageSize: &pageSizeDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the trades params
func (o *TradesParams) WithTimeout(timeout time.Duration) *TradesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the trades params
func (o *TradesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the trades params
func (o *TradesParams) WithContext(ctx context.Context) *TradesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the trades params
func (o *TradesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the trades params
func (o *TradesParams) WithHTTPClient(client *http.Client) *TradesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the trades params
func (o *TradesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the trades params
func (o *TradesParams) WithCursor(cursor *string) *TradesParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the trades params
func (o *TradesParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithEndAt adds the endAt to the trades params
func (o *TradesParams) WithEndAt(endAt *int64) *TradesParams {
	o.SetEndAt(endAt)
	return o
}

// SetEndAt adds the endAt to the trades params
func (o *TradesParams) SetEndAt(endAt *int64) {
	o.EndAt = endAt
}

// WithMarket adds the market to the trades params
func (o *TradesParams) WithMarket(market string) *TradesParams {
	o.SetMarket(market)
	return o
}

// SetMarket adds the market to the trades params
func (o *TradesParams) SetMarket(market string) {
	o.Market = market
}

// WithPageSize adds the pageSize to the trades params
func (o *TradesParams) WithPageSize(pageSize *int64) *TradesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the trades params
func (o *TradesParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithStartAt adds the startAt to the trades params
func (o *TradesParams) WithStartAt(startAt *int64) *TradesParams {
	o.SetStartAt(startAt)
	return o
}

// SetStartAt adds the startAt to the trades params
func (o *TradesParams) SetStartAt(startAt *int64) {
	o.StartAt = startAt
}

// WriteToRequest writes these params to a swagger request
func (o *TradesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string

		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {

			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}
	}

	if o.EndAt != nil {

		// query param end_at
		var qrEndAt int64

		if o.EndAt != nil {
			qrEndAt = *o.EndAt
		}
		qEndAt := swag.FormatInt64(qrEndAt)
		if qEndAt != "" {

			if err := r.SetQueryParam("end_at", qEndAt); err != nil {
				return err
			}
		}
	}

	// query param market
	qrMarket := o.Market
	qMarket := qrMarket
	if qMarket != "" {

		if err := r.SetQueryParam("market", qMarket); err != nil {
			return err
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.StartAt != nil {

		// query param start_at
		var qrStartAt int64

		if o.StartAt != nil {
			qrStartAt = *o.StartAt
		}
		qStartAt := swag.FormatInt64(qrStartAt)
		if qStartAt != "" {

			if err := r.SetQueryParam("start_at", qStartAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
