// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// OrdersCancelByClientIDReader is a Reader for the OrdersCancelByClientID structure.
type OrdersCancelByClientIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrdersCancelByClientIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOrdersCancelByClientIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOrdersCancelByClientIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /orders/by_client_id/{client_id}] orders-cancel-by-client-id", response, response.Code())
	}
}

// NewOrdersCancelByClientIDNoContent creates a OrdersCancelByClientIDNoContent with default headers values
func NewOrdersCancelByClientIDNoContent() *OrdersCancelByClientIDNoContent {
	return &OrdersCancelByClientIDNoContent{}
}

/*
OrdersCancelByClientIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type OrdersCancelByClientIDNoContent struct {
}

// IsSuccess returns true when this orders cancel by client Id no content response has a 2xx status code
func (o *OrdersCancelByClientIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this orders cancel by client Id no content response has a 3xx status code
func (o *OrdersCancelByClientIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this orders cancel by client Id no content response has a 4xx status code
func (o *OrdersCancelByClientIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this orders cancel by client Id no content response has a 5xx status code
func (o *OrdersCancelByClientIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this orders cancel by client Id no content response a status code equal to that given
func (o *OrdersCancelByClientIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the orders cancel by client Id no content response
func (o *OrdersCancelByClientIDNoContent) Code() int {
	return 204
}

func (o *OrdersCancelByClientIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /orders/by_client_id/{client_id}][%d] ordersCancelByClientIdNoContent", 204)
}

func (o *OrdersCancelByClientIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /orders/by_client_id/{client_id}][%d] ordersCancelByClientIdNoContent", 204)
}

func (o *OrdersCancelByClientIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrdersCancelByClientIDBadRequest creates a OrdersCancelByClientIDBadRequest with default headers values
func NewOrdersCancelByClientIDBadRequest() *OrdersCancelByClientIDBadRequest {
	return &OrdersCancelByClientIDBadRequest{}
}

/*
OrdersCancelByClientIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type OrdersCancelByClientIDBadRequest struct {
	Payload *models.ResponsesAPIError
}

// IsSuccess returns true when this orders cancel by client Id bad request response has a 2xx status code
func (o *OrdersCancelByClientIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this orders cancel by client Id bad request response has a 3xx status code
func (o *OrdersCancelByClientIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this orders cancel by client Id bad request response has a 4xx status code
func (o *OrdersCancelByClientIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this orders cancel by client Id bad request response has a 5xx status code
func (o *OrdersCancelByClientIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this orders cancel by client Id bad request response a status code equal to that given
func (o *OrdersCancelByClientIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the orders cancel by client Id bad request response
func (o *OrdersCancelByClientIDBadRequest) Code() int {
	return 400
}

func (o *OrdersCancelByClientIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /orders/by_client_id/{client_id}][%d] ordersCancelByClientIdBadRequest %s", 400, payload)
}

func (o *OrdersCancelByClientIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /orders/by_client_id/{client_id}][%d] ordersCancelByClientIdBadRequest %s", 400, payload)
}

func (o *OrdersCancelByClientIDBadRequest) GetPayload() *models.ResponsesAPIError {
	return o.Payload
}

func (o *OrdersCancelByClientIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponsesAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
