// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// NewOrdersModifyParams creates a new OrdersModifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrdersModifyParams() *OrdersModifyParams {
	return &OrdersModifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrdersModifyParamsWithTimeout creates a new OrdersModifyParams object
// with the ability to set a timeout on a request.
func NewOrdersModifyParamsWithTimeout(timeout time.Duration) *OrdersModifyParams {
	return &OrdersModifyParams{
		timeout: timeout,
	}
}

// NewOrdersModifyParamsWithContext creates a new OrdersModifyParams object
// with the ability to set a context for a request.
func NewOrdersModifyParamsWithContext(ctx context.Context) *OrdersModifyParams {
	return &OrdersModifyParams{
		Context: ctx,
	}
}

// NewOrdersModifyParamsWithHTTPClient creates a new OrdersModifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrdersModifyParamsWithHTTPClient(client *http.Client) *OrdersModifyParams {
	return &OrdersModifyParams{
		HTTPClient: client,
	}
}

/*
OrdersModifyParams contains all the parameters to send to the API endpoint

	for the orders modify operation.

	Typically these are written to a http.Request.
*/
type OrdersModifyParams struct {

	/* OrderID.

	   Order Id
	*/
	OrderID string

	/* OrderRequest.

	   Modify Order Request
	*/
	OrderRequest *models.RequestsModifyOrderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the orders modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersModifyParams) WithDefaults() *OrdersModifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the orders modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersModifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the orders modify params
func (o *OrdersModifyParams) WithTimeout(timeout time.Duration) *OrdersModifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the orders modify params
func (o *OrdersModifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the orders modify params
func (o *OrdersModifyParams) WithContext(ctx context.Context) *OrdersModifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the orders modify params
func (o *OrdersModifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the orders modify params
func (o *OrdersModifyParams) WithHTTPClient(client *http.Client) *OrdersModifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the orders modify params
func (o *OrdersModifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderID adds the orderID to the orders modify params
func (o *OrdersModifyParams) WithOrderID(orderID string) *OrdersModifyParams {
	o.SetOrderID(orderID)
	return o
}

// SetOrderID adds the orderId to the orders modify params
func (o *OrdersModifyParams) SetOrderID(orderID string) {
	o.OrderID = orderID
}

// WithOrderRequest adds the orderRequest to the orders modify params
func (o *OrdersModifyParams) WithOrderRequest(orderRequest *models.RequestsModifyOrderRequest) *OrdersModifyParams {
	o.SetOrderRequest(orderRequest)
	return o
}

// SetOrderRequest adds the orderRequest to the orders modify params
func (o *OrdersModifyParams) SetOrderRequest(orderRequest *models.RequestsModifyOrderRequest) {
	o.OrderRequest = orderRequest
}

// WriteToRequest writes these params to a swagger request
func (o *OrdersModifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param order_id
	if err := r.SetPathParam("order_id", o.OrderID); err != nil {
		return err
	}
	if o.OrderRequest != nil {
		if err := r.SetBodyParam(o.OrderRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
