// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOrdersGetByClientIDParams creates a new OrdersGetByClientIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrdersGetByClientIDParams() *OrdersGetByClientIDParams {
	return &OrdersGetByClientIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrdersGetByClientIDParamsWithTimeout creates a new OrdersGetByClientIDParams object
// with the ability to set a timeout on a request.
func NewOrdersGetByClientIDParamsWithTimeout(timeout time.Duration) *OrdersGetByClientIDParams {
	return &OrdersGetByClientIDParams{
		timeout: timeout,
	}
}

// NewOrdersGetByClientIDParamsWithContext creates a new OrdersGetByClientIDParams object
// with the ability to set a context for a request.
func NewOrdersGetByClientIDParamsWithContext(ctx context.Context) *OrdersGetByClientIDParams {
	return &OrdersGetByClientIDParams{
		Context: ctx,
	}
}

// NewOrdersGetByClientIDParamsWithHTTPClient creates a new OrdersGetByClientIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrdersGetByClientIDParamsWithHTTPClient(client *http.Client) *OrdersGetByClientIDParams {
	return &OrdersGetByClientIDParams{
		HTTPClient: client,
	}
}

/*
OrdersGetByClientIDParams contains all the parameters to send to the API endpoint

	for the orders get by client id operation.

	Typically these are written to a http.Request.
*/
type OrdersGetByClientIDParams struct {

	/* ClientID.

	   Client Order Id
	*/
	ClientID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the orders get by client id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersGetByClientIDParams) WithDefaults() *OrdersGetByClientIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the orders get by client id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersGetByClientIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the orders get by client id params
func (o *OrdersGetByClientIDParams) WithTimeout(timeout time.Duration) *OrdersGetByClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the orders get by client id params
func (o *OrdersGetByClientIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the orders get by client id params
func (o *OrdersGetByClientIDParams) WithContext(ctx context.Context) *OrdersGetByClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the orders get by client id params
func (o *OrdersGetByClientIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the orders get by client id params
func (o *OrdersGetByClientIDParams) WithHTTPClient(client *http.Client) *OrdersGetByClientIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the orders get by client id params
func (o *OrdersGetByClientIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the orders get by client id params
func (o *OrdersGetByClientIDParams) WithClientID(clientID string) *OrdersGetByClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the orders get by client id params
func (o *OrdersGetByClientIDParams) SetClientID(clientID string) {
	o.ClientID = clientID
}

// WriteToRequest writes these params to a swagger request
func (o *OrdersGetByClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param client_id
	if err := r.SetPathParam("client_id", o.ClientID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
