// Code generated by go-swagger; DO NOT EDIT.

package orders

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trishtzy/go-paradex/models"
)

// NewOrdersNewParams creates a new OrdersNewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrdersNewParams() *OrdersNewParams {
	return &OrdersNewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOrdersNewParamsWithTimeout creates a new OrdersNewParams object
// with the ability to set a timeout on a request.
func NewOrdersNewParamsWithTimeout(timeout time.Duration) *OrdersNewParams {
	return &OrdersNewParams{
		timeout: timeout,
	}
}

// NewOrdersNewParamsWithContext creates a new OrdersNewParams object
// with the ability to set a context for a request.
func NewOrdersNewParamsWithContext(ctx context.Context) *OrdersNewParams {
	return &OrdersNewParams{
		Context: ctx,
	}
}

// NewOrdersNewParamsWithHTTPClient creates a new OrdersNewParams object
// with the ability to set a custom HTTPClient for a request.
func NewOrdersNewParamsWithHTTPClient(client *http.Client) *OrdersNewParams {
	return &OrdersNewParams{
		HTTPClient: client,
	}
}

/*
OrdersNewParams contains all the parameters to send to the API endpoint

	for the orders new operation.

	Typically these are written to a http.Request.
*/
type OrdersNewParams struct {

	/* Params.

	   Order content
	*/
	Params *models.RequestsOrderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the orders new params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersNewParams) WithDefaults() *OrdersNewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the orders new params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrdersNewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the orders new params
func (o *OrdersNewParams) WithTimeout(timeout time.Duration) *OrdersNewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the orders new params
func (o *OrdersNewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the orders new params
func (o *OrdersNewParams) WithContext(ctx context.Context) *OrdersNewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the orders new params
func (o *OrdersNewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the orders new params
func (o *OrdersNewParams) WithHTTPClient(client *http.Client) *OrdersNewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the orders new params
func (o *OrdersNewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithParams adds the params to the orders new params
func (o *OrdersNewParams) WithParams(params *models.RequestsOrderRequest) *OrdersNewParams {
	o.SetParams(params)
	return o
}

// SetParams adds the params to the orders new params
func (o *OrdersNewParams) SetParams(params *models.RequestsOrderRequest) {
	o.Params = params
}

// WriteToRequest writes these params to a swagger request
func (o *OrdersNewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Params != nil {
		if err := r.SetBodyParam(o.Params); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
