// Code generated by go-swagger; DO NOT EDIT.

package liquidations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLiquidationsParams creates a new GetLiquidationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLiquidationsParams() *GetLiquidationsParams {
	return &GetLiquidationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLiquidationsParamsWithTimeout creates a new GetLiquidationsParams object
// with the ability to set a timeout on a request.
func NewGetLiquidationsParamsWithTimeout(timeout time.Duration) *GetLiquidationsParams {
	return &GetLiquidationsParams{
		timeout: timeout,
	}
}

// NewGetLiquidationsParamsWithContext creates a new GetLiquidationsParams object
// with the ability to set a context for a request.
func NewGetLiquidationsParamsWithContext(ctx context.Context) *GetLiquidationsParams {
	return &GetLiquidationsParams{
		Context: ctx,
	}
}

// NewGetLiquidationsParamsWithHTTPClient creates a new GetLiquidationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLiquidationsParamsWithHTTPClient(client *http.Client) *GetLiquidationsParams {
	return &GetLiquidationsParams{
		HTTPClient: client,
	}
}

/*
GetLiquidationsParams contains all the parameters to send to the API endpoint

	for the get liquidations operation.

	Typically these are written to a http.Request.
*/
type GetLiquidationsParams struct {

	/* From.

	   Start Time (unix time millisecond)
	*/
	From *int64

	/* To.

	   End Time (unix time millisecond)
	*/
	To *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get liquidations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLiquidationsParams) WithDefaults() *GetLiquidationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get liquidations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLiquidationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get liquidations params
func (o *GetLiquidationsParams) WithTimeout(timeout time.Duration) *GetLiquidationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get liquidations params
func (o *GetLiquidationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get liquidations params
func (o *GetLiquidationsParams) WithContext(ctx context.Context) *GetLiquidationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get liquidations params
func (o *GetLiquidationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get liquidations params
func (o *GetLiquidationsParams) WithHTTPClient(client *http.Client) *GetLiquidationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get liquidations params
func (o *GetLiquidationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get liquidations params
func (o *GetLiquidationsParams) WithFrom(from *int64) *GetLiquidationsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get liquidations params
func (o *GetLiquidationsParams) SetFrom(from *int64) {
	o.From = from
}

// WithTo adds the to to the get liquidations params
func (o *GetLiquidationsParams) WithTo(to *int64) *GetLiquidationsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the get liquidations params
func (o *GetLiquidationsParams) SetTo(to *int64) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *GetLiquidationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom int64

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := swag.FormatInt64(qrFrom)
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo int64

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := swag.FormatInt64(qrTo)
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
