// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Messagesv1MarginType messagesv1 margin type
//
// swagger:model messagesv1.MarginType
type Messagesv1MarginType int64

// for schema
var messagesv1MarginTypeEnum []interface{}

func init() {
	var res []Messagesv1MarginType
	if err := json.Unmarshal([]byte(`[0,1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		messagesv1MarginTypeEnum = append(messagesv1MarginTypeEnum, v)
	}
}

func (m Messagesv1MarginType) validateMessagesv1MarginTypeEnum(path, location string, value Messagesv1MarginType) error {
	if err := validate.EnumCase(path, location, value, messagesv1MarginTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this messagesv1 margin type
func (m Messagesv1MarginType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMessagesv1MarginTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this messagesv1 margin type based on context it is used
func (m Messagesv1MarginType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
