// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RequestsAccountMarginRequest requests account margin request
//
// swagger:model requests.AccountMarginRequest
type RequestsAccountMarginRequest struct {

	// Leverage value (1 up to market's maximum leverage)
	// Example: 10
	// Required: true
	Leverage *int64 `json:"leverage"`

	// Margin type (CROSS or ISOLATED)
	// Example: CROSS
	// Required: true
	MarginType *string `json:"margin_type"`
}

// Validate validates this requests account margin request
func (m *RequestsAccountMarginRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLeverage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMarginType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestsAccountMarginRequest) validateLeverage(formats strfmt.Registry) error {

	if err := validate.Required("leverage", "body", m.Leverage); err != nil {
		return err
	}

	return nil
}

func (m *RequestsAccountMarginRequest) validateMarginType(formats strfmt.Registry) error {

	if err := validate.Required("margin_type", "body", m.MarginType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this requests account margin request based on context it is used
func (m *RequestsAccountMarginRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestsAccountMarginRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestsAccountMarginRequest) UnmarshalBinary(b []byte) error {
	var res RequestsAccountMarginRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
