// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestsOnboarding requests onboarding
//
// swagger:model requests.Onboarding
type RequestsOnboarding struct {

	// Public key of the user being onboarded.
	// Example: 0x3d9f2b2e5f50c1aade60ca540368cd7490160f41270c192c05729fe35b656a9
	PublicKey string `json:"public_key,omitempty"`

	// Referral code of the user who referred the user being onboarded.
	// Example: cryptofox8
	ReferralCode string `json:"referral_code,omitempty"`
}

// Validate validates this requests onboarding
func (m *RequestsOnboarding) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this requests onboarding based on context it is used
func (m *RequestsOnboarding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestsOnboarding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestsOnboarding) UnmarshalBinary(b []byte) error {
	var res RequestsOnboarding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
