// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesProgramsEligibility responses programs eligibility
//
// swagger:model responses.ProgramsEligibility
type ResponsesProgramsEligibility struct {

	// affiliate
	// Example: Pending
	Affiliate string `json:"affiliate,omitempty"`

	// fee
	// Example: True
	Fee string `json:"fee,omitempty"`

	// maker
	// Example: True
	Maker string `json:"maker,omitempty"`

	// referral
	// Example: False
	Referral string `json:"referral,omitempty"`
}

// Validate validates this responses programs eligibility
func (m *ResponsesProgramsEligibility) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses programs eligibility based on context it is used
func (m *ResponsesProgramsEligibility) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesProgramsEligibility) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesProgramsEligibility) UnmarshalBinary(b []byte) error {
	var res ResponsesProgramsEligibility
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
