// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesAccountSummaryResponse responses account summary response
//
// swagger:model responses.AccountSummaryResponse
type ResponsesAccountSummaryResponse struct {

	// User's starknet account
	// Example: 0x495d2eb5236a12b8b4ad7d3849ce6a203ce21c43f473c248dfd5ce70d9454fa
	Account string `json:"account,omitempty"`

	// Current account value [with unrealized P&Ls]
	// Example: 136285.06918911
	AccountValue string `json:"account_value,omitempty"`

	// Free collateral available (Account value in excess of Initial Margin required)
	// Example: 73276.47229774
	FreeCollateral string `json:"free_collateral,omitempty"`

	// Amount required to open trade for the existing positions
	// Example: 63008.59689218
	InitialMarginRequirement string `json:"initial_margin_requirement,omitempty"`

	// Amount required to maintain exisiting positions
	// Example: 31597.25239676
	MaintenanceMarginRequirement string `json:"maintenance_margin_requirement,omitempty"`

	// Acc value in excess of maintenance margin required
	// Example: 104687.8167956
	MarginCushion string `json:"margin_cushion,omitempty"`

	// Unique increasing number (non-sequential) that is assigned to this account update. Can be used to deduplicate multiple feeds
	// Example: 1681471234972000000
	SeqNo int64 `json:"seq_no,omitempty"`

	// Settlement asset for the account
	// Example: USDC
	SettlementAsset string `json:"settlement_asset,omitempty"`

	// Status of the acc - like ACTIVE, LIQUIDATION
	// Example: ACTIVE
	Status string `json:"status,omitempty"`

	// User's total collateral
	// Example: 123003.62047353
	TotalCollateral string `json:"total_collateral,omitempty"`

	// Account last updated time
	// Example: 1681471234972
	UpdatedAt int64 `json:"updated_at,omitempty"`
}

// Validate validates this responses account summary response
func (m *ResponsesAccountSummaryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses account summary response based on context it is used
func (m *ResponsesAccountSummaryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesAccountSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesAccountSummaryResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesAccountSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
