// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// ResponsesErrorCode responses error code
//
// swagger:model responses.ErrorCode
type ResponsesErrorCode string

func NewResponsesErrorCode(value ResponsesErrorCode) *ResponsesErrorCode {
	return &value
}

// Pointer returns a pointer to a freshly-allocated ResponsesErrorCode.
func (m ResponsesErrorCode) Pointer() *ResponsesErrorCode {
	return &m
}

const (

	// ResponsesErrorCodeVALIDATIONERROR captures enum value "VALIDATION_ERROR"
	ResponsesErrorCodeVALIDATIONERROR ResponsesErrorCode = "VALIDATION_ERROR"

	// ResponsesErrorCodeBINDINGERROR captures enum value "BINDING_ERROR"
	ResponsesErrorCodeBINDINGERROR ResponsesErrorCode = "BINDING_ERROR"

	// ResponsesErrorCodeINTERNALERROR captures enum value "INTERNAL_ERROR"
	ResponsesErrorCodeINTERNALERROR ResponsesErrorCode = "INTERNAL_ERROR"

	// ResponsesErrorCodeNOTFOUND captures enum value "NOT_FOUND"
	ResponsesErrorCodeNOTFOUND ResponsesErrorCode = "NOT_FOUND"

	// ResponsesErrorCodeSERVICEUNAVAILABLE captures enum value "SERVICE_UNAVAILABLE"
	ResponsesErrorCodeSERVICEUNAVAILABLE ResponsesErrorCode = "SERVICE_UNAVAILABLE"

	// ResponsesErrorCodeINVALIDREQUESTPARAMETER captures enum value "INVALID_REQUEST_PARAMETER"
	ResponsesErrorCodeINVALIDREQUESTPARAMETER ResponsesErrorCode = "INVALID_REQUEST_PARAMETER"

	// ResponsesErrorCodeORDERIDNOTFOUND captures enum value "ORDER_ID_NOT_FOUND"
	ResponsesErrorCodeORDERIDNOTFOUND ResponsesErrorCode = "ORDER_ID_NOT_FOUND"

	// ResponsesErrorCodeORDERISCLOSED captures enum value "ORDER_IS_CLOSED"
	ResponsesErrorCodeORDERISCLOSED ResponsesErrorCode = "ORDER_IS_CLOSED"

	// ResponsesErrorCodeORDERISNOTOPEN captures enum value "ORDER_IS_NOT_OPEN"
	ResponsesErrorCodeORDERISNOTOPEN ResponsesErrorCode = "ORDER_IS_NOT_OPEN"

	// ResponsesErrorCodeINVALIDORDERSIZE captures enum value "INVALID_ORDER_SIZE"
	ResponsesErrorCodeINVALIDORDERSIZE ResponsesErrorCode = "INVALID_ORDER_SIZE"

	// ResponsesErrorCodeCLIENTORDERIDNOTFOUND captures enum value "CLIENT_ORDER_ID_NOT_FOUND"
	ResponsesErrorCodeCLIENTORDERIDNOTFOUND ResponsesErrorCode = "CLIENT_ORDER_ID_NOT_FOUND"

	// ResponsesErrorCodeDUPLICATEDCLIENTID captures enum value "DUPLICATED_CLIENT_ID"
	ResponsesErrorCodeDUPLICATEDCLIENTID ResponsesErrorCode = "DUPLICATED_CLIENT_ID"

	// ResponsesErrorCodeINVALIDPRICEPRECISION captures enum value "INVALID_PRICE_PRECISION"
	ResponsesErrorCodeINVALIDPRICEPRECISION ResponsesErrorCode = "INVALID_PRICE_PRECISION"

	// ResponsesErrorCodeINVALIDSYMBOL captures enum value "INVALID_SYMBOL"
	ResponsesErrorCodeINVALIDSYMBOL ResponsesErrorCode = "INVALID_SYMBOL"

	// ResponsesErrorCodeINVALIDTOKEN captures enum value "INVALID_TOKEN"
	ResponsesErrorCodeINVALIDTOKEN ResponsesErrorCode = "INVALID_TOKEN"

	// ResponsesErrorCodeINVALIDETHEREUMADDRESS captures enum value "INVALID_ETHEREUM_ADDRESS"
	ResponsesErrorCodeINVALIDETHEREUMADDRESS ResponsesErrorCode = "INVALID_ETHEREUM_ADDRESS"

	// ResponsesErrorCodeINVALIDETHEREUMSIGNATURE captures enum value "INVALID_ETHEREUM_SIGNATURE"
	ResponsesErrorCodeINVALIDETHEREUMSIGNATURE ResponsesErrorCode = "INVALID_ETHEREUM_SIGNATURE"

	// ResponsesErrorCodeINVALIDSTARKNETADDRESS captures enum value "INVALID_STARKNET_ADDRESS"
	ResponsesErrorCodeINVALIDSTARKNETADDRESS ResponsesErrorCode = "INVALID_STARKNET_ADDRESS"

	// ResponsesErrorCodeINVALIDSTARKNETSIGNATURE captures enum value "INVALID_STARKNET_SIGNATURE"
	ResponsesErrorCodeINVALIDSTARKNETSIGNATURE ResponsesErrorCode = "INVALID_STARKNET_SIGNATURE"

	// ResponsesErrorCodeSTARKNETSIGNATUREVERIFICATIONFAILED captures enum value "STARKNET_SIGNATURE_VERIFICATION_FAILED"
	ResponsesErrorCodeSTARKNETSIGNATUREVERIFICATIONFAILED ResponsesErrorCode = "STARKNET_SIGNATURE_VERIFICATION_FAILED"

	// ResponsesErrorCodeBADSTARKNETREQUEST captures enum value "BAD_STARKNET_REQUEST"
	ResponsesErrorCodeBADSTARKNETREQUEST ResponsesErrorCode = "BAD_STARKNET_REQUEST"

	// ResponsesErrorCodeETHEREUMSIGNERMISMATCH captures enum value "ETHEREUM_SIGNER_MISMATCH"
	ResponsesErrorCodeETHEREUMSIGNERMISMATCH ResponsesErrorCode = "ETHEREUM_SIGNER_MISMATCH"

	// ResponsesErrorCodeETHEREUMHASHMISMATCH captures enum value "ETHEREUM_HASH_MISMATCH"
	ResponsesErrorCodeETHEREUMHASHMISMATCH ResponsesErrorCode = "ETHEREUM_HASH_MISMATCH"

	// ResponsesErrorCodeNOTONBOARDED captures enum value "NOT_ONBOARDED"
	ResponsesErrorCodeNOTONBOARDED ResponsesErrorCode = "NOT_ONBOARDED"

	// ResponsesErrorCodeINVALIDTIMESTAMP captures enum value "INVALID_TIMESTAMP"
	ResponsesErrorCodeINVALIDTIMESTAMP ResponsesErrorCode = "INVALID_TIMESTAMP"

	// ResponsesErrorCodeINVALIDSIGNATUREEXPIRATION captures enum value "INVALID_SIGNATURE_EXPIRATION"
	ResponsesErrorCodeINVALIDSIGNATUREEXPIRATION ResponsesErrorCode = "INVALID_SIGNATURE_EXPIRATION"

	// ResponsesErrorCodeACCOUNTNOTFOUND captures enum value "ACCOUNT_NOT_FOUND"
	ResponsesErrorCodeACCOUNTNOTFOUND ResponsesErrorCode = "ACCOUNT_NOT_FOUND"

	// ResponsesErrorCodeINVALIDORDERSIGNATURE captures enum value "INVALID_ORDER_SIGNATURE"
	ResponsesErrorCodeINVALIDORDERSIGNATURE ResponsesErrorCode = "INVALID_ORDER_SIGNATURE"

	// ResponsesErrorCodePUBLICKEYINVALID captures enum value "PUBLIC_KEY_INVALID"
	ResponsesErrorCodePUBLICKEYINVALID ResponsesErrorCode = "PUBLIC_KEY_INVALID"

	// ResponsesErrorCodeUNAUTHORIZEDETHEREUMADDRESS captures enum value "UNAUTHORIZED_ETHEREUM_ADDRESS"
	ResponsesErrorCodeUNAUTHORIZEDETHEREUMADDRESS ResponsesErrorCode = "UNAUTHORIZED_ETHEREUM_ADDRESS"

	// ResponsesErrorCodeETHEREUMADDRESSALREADYONBOARDED captures enum value "ETHEREUM_ADDRESS_ALREADY_ONBOARDED"
	ResponsesErrorCodeETHEREUMADDRESSALREADYONBOARDED ResponsesErrorCode = "ETHEREUM_ADDRESS_ALREADY_ONBOARDED"

	// ResponsesErrorCodeMARKETNOTFOUND captures enum value "MARKET_NOT_FOUND"
	ResponsesErrorCodeMARKETNOTFOUND ResponsesErrorCode = "MARKET_NOT_FOUND"

	// ResponsesErrorCodeALLOWLISTENTRYNOTFOUND captures enum value "ALLOWLIST_ENTRY_NOT_FOUND"
	ResponsesErrorCodeALLOWLISTENTRYNOTFOUND ResponsesErrorCode = "ALLOWLIST_ENTRY_NOT_FOUND"

	// ResponsesErrorCodeUSERNAMEINUSE captures enum value "USERNAME_IN_USE"
	ResponsesErrorCodeUSERNAMEINUSE ResponsesErrorCode = "USERNAME_IN_USE"

	// ResponsesErrorCodeGEOIPBLOCK captures enum value "GEO_IP_BLOCK"
	ResponsesErrorCodeGEOIPBLOCK ResponsesErrorCode = "GEO_IP_BLOCK"

	// ResponsesErrorCodeETHEREUMADDRESSBLOCKED captures enum value "ETHEREUM_ADDRESS_BLOCKED"
	ResponsesErrorCodeETHEREUMADDRESSBLOCKED ResponsesErrorCode = "ETHEREUM_ADDRESS_BLOCKED"

	// ResponsesErrorCodePROGRAMNOTFOUND captures enum value "PROGRAM_NOT_FOUND"
	ResponsesErrorCodePROGRAMNOTFOUND ResponsesErrorCode = "PROGRAM_NOT_FOUND"

	// ResponsesErrorCodePROGRAMNOTSUPPORTED captures enum value "PROGRAM_NOT_SUPPORTED"
	ResponsesErrorCodePROGRAMNOTSUPPORTED ResponsesErrorCode = "PROGRAM_NOT_SUPPORTED"

	// ResponsesErrorCodeINVALIDDASHBOARD captures enum value "INVALID_DASHBOARD"
	ResponsesErrorCodeINVALIDDASHBOARD ResponsesErrorCode = "INVALID_DASHBOARD"

	// ResponsesErrorCodeMARKETNOTOPEN captures enum value "MARKET_NOT_OPEN"
	ResponsesErrorCodeMARKETNOTOPEN ResponsesErrorCode = "MARKET_NOT_OPEN"

	// ResponsesErrorCodeINVALIDREFERRALCODE captures enum value "INVALID_REFERRAL_CODE"
	ResponsesErrorCodeINVALIDREFERRALCODE ResponsesErrorCode = "INVALID_REFERRAL_CODE"

	// ResponsesErrorCodeREQUESTNOTALLOWED captures enum value "REQUEST_NOT_ALLOWED"
	ResponsesErrorCodeREQUESTNOTALLOWED ResponsesErrorCode = "REQUEST_NOT_ALLOWED"

	// ResponsesErrorCodePARENTADDRESSALREADYONBOARDED captures enum value "PARENT_ADDRESS_ALREADY_ONBOARDED"
	ResponsesErrorCodePARENTADDRESSALREADYONBOARDED ResponsesErrorCode = "PARENT_ADDRESS_ALREADY_ONBOARDED"

	// ResponsesErrorCodeINVALIDPARENTACCOUNT captures enum value "INVALID_PARENT_ACCOUNT"
	ResponsesErrorCodeINVALIDPARENTACCOUNT ResponsesErrorCode = "INVALID_PARENT_ACCOUNT"

	// ResponsesErrorCodeINVALIDVAULTOPERATORCHAIN captures enum value "INVALID_VAULT_OPERATOR_CHAIN"
	ResponsesErrorCodeINVALIDVAULTOPERATORCHAIN ResponsesErrorCode = "INVALID_VAULT_OPERATOR_CHAIN"

	// ResponsesErrorCodeVAULTOPERATORALREADYONBOARDED captures enum value "VAULT_OPERATOR_ALREADY_ONBOARDED"
	ResponsesErrorCodeVAULTOPERATORALREADYONBOARDED ResponsesErrorCode = "VAULT_OPERATOR_ALREADY_ONBOARDED"

	// ResponsesErrorCodeVAULTNAMEINUSE captures enum value "VAULT_NAME_IN_USE"
	ResponsesErrorCodeVAULTNAMEINUSE ResponsesErrorCode = "VAULT_NAME_IN_USE"

	// ResponsesErrorCodeVAULTNOTFOUND captures enum value "VAULT_NOT_FOUND"
	ResponsesErrorCodeVAULTNOTFOUND ResponsesErrorCode = "VAULT_NOT_FOUND"

	// ResponsesErrorCodeVAULTSTRATEGYNOTFOUND captures enum value "VAULT_STRATEGY_NOT_FOUND"
	ResponsesErrorCodeVAULTSTRATEGYNOTFOUND ResponsesErrorCode = "VAULT_STRATEGY_NOT_FOUND"

	// ResponsesErrorCodeVAULTLIMITREACHED captures enum value "VAULT_LIMIT_REACHED"
	ResponsesErrorCodeVAULTLIMITREACHED ResponsesErrorCode = "VAULT_LIMIT_REACHED"

	// ResponsesErrorCodeBATCHSIZEOUTOFRANGE captures enum value "BATCH_SIZE_OUT_OF_RANGE"
	ResponsesErrorCodeBATCHSIZEOUTOFRANGE ResponsesErrorCode = "BATCH_SIZE_OUT_OF_RANGE"

	// ResponsesErrorCodeISOLATEDMARKETACCOUNTMISMATCH captures enum value "ISOLATED_MARKET_ACCOUNT_MISMATCH"
	ResponsesErrorCodeISOLATEDMARKETACCOUNTMISMATCH ResponsesErrorCode = "ISOLATED_MARKET_ACCOUNT_MISMATCH"

	// ResponsesErrorCodeNOACCESSTOMARKET captures enum value "NO_ACCESS_TO_MARKET"
	ResponsesErrorCodeNOACCESSTOMARKET ResponsesErrorCode = "NO_ACCESS_TO_MARKET"

	// ResponsesErrorCodePOINTSSUMMARYNOTFOUND captures enum value "POINTS_SUMMARY_NOT_FOUND"
	ResponsesErrorCodePOINTSSUMMARYNOTFOUND ResponsesErrorCode = "POINTS_SUMMARY_NOT_FOUND"

	// ResponsesErrorCodeALGOIDNOTFOUND captures enum value "ALGO_ID_NOT_FOUND"
	ResponsesErrorCodeALGOIDNOTFOUND ResponsesErrorCode = "ALGO_ID_NOT_FOUND"

	// ResponsesErrorCodeINVALIDDERIVATIONPATH captures enum value "INVALID_DERIVATION_PATH"
	ResponsesErrorCodeINVALIDDERIVATIONPATH ResponsesErrorCode = "INVALID_DERIVATION_PATH"

	// ResponsesErrorCodePROFILESTATSNOTFOUND captures enum value "PROFILE_STATS_NOT_FOUND"
	ResponsesErrorCodePROFILESTATSNOTFOUND ResponsesErrorCode = "PROFILE_STATS_NOT_FOUND"

	// ResponsesErrorCodeINVALIDCHAIN captures enum value "INVALID_CHAIN"
	ResponsesErrorCodeINVALIDCHAIN ResponsesErrorCode = "INVALID_CHAIN"

	// ResponsesErrorCodeINVALIDLAYERSWAPSWAP captures enum value "INVALID_LAYERSWAP_SWAP"
	ResponsesErrorCodeINVALIDLAYERSWAPSWAP ResponsesErrorCode = "INVALID_LAYERSWAP_SWAP"

	// ResponsesErrorCodeSOCIALUSERNAMEINUSE captures enum value "SOCIAL_USERNAME_IN_USE"
	ResponsesErrorCodeSOCIALUSERNAMEINUSE ResponsesErrorCode = "SOCIAL_USERNAME_IN_USE"
)

// for schema
var responsesErrorCodeEnum []interface{}

func init() {
	var res []ResponsesErrorCode
	if err := json.Unmarshal([]byte(`["VALIDATION_ERROR","BINDING_ERROR","INTERNAL_ERROR","NOT_FOUND","SERVICE_UNAVAILABLE","INVALID_REQUEST_PARAMETER","ORDER_ID_NOT_FOUND","ORDER_IS_CLOSED","ORDER_IS_NOT_OPEN","INVALID_ORDER_SIZE","CLIENT_ORDER_ID_NOT_FOUND","DUPLICATED_CLIENT_ID","INVALID_PRICE_PRECISION","INVALID_SYMBOL","INVALID_TOKEN","INVALID_ETHEREUM_ADDRESS","INVALID_ETHEREUM_SIGNATURE","INVALID_STARKNET_ADDRESS","INVALID_STARKNET_SIGNATURE","STARKNET_SIGNATURE_VERIFICATION_FAILED","BAD_STARKNET_REQUEST","ETHEREUM_SIGNER_MISMATCH","ETHEREUM_HASH_MISMATCH","NOT_ONBOARDED","INVALID_TIMESTAMP","INVALID_SIGNATURE_EXPIRATION","ACCOUNT_NOT_FOUND","INVALID_ORDER_SIGNATURE","PUBLIC_KEY_INVALID","UNAUTHORIZED_ETHEREUM_ADDRESS","ETHEREUM_ADDRESS_ALREADY_ONBOARDED","MARKET_NOT_FOUND","ALLOWLIST_ENTRY_NOT_FOUND","USERNAME_IN_USE","GEO_IP_BLOCK","ETHEREUM_ADDRESS_BLOCKED","PROGRAM_NOT_FOUND","PROGRAM_NOT_SUPPORTED","INVALID_DASHBOARD","MARKET_NOT_OPEN","INVALID_REFERRAL_CODE","REQUEST_NOT_ALLOWED","PARENT_ADDRESS_ALREADY_ONBOARDED","INVALID_PARENT_ACCOUNT","INVALID_VAULT_OPERATOR_CHAIN","VAULT_OPERATOR_ALREADY_ONBOARDED","VAULT_NAME_IN_USE","VAULT_NOT_FOUND","VAULT_STRATEGY_NOT_FOUND","VAULT_LIMIT_REACHED","BATCH_SIZE_OUT_OF_RANGE","ISOLATED_MARKET_ACCOUNT_MISMATCH","NO_ACCESS_TO_MARKET","POINTS_SUMMARY_NOT_FOUND","ALGO_ID_NOT_FOUND","INVALID_DERIVATION_PATH","PROFILE_STATS_NOT_FOUND","INVALID_CHAIN","INVALID_LAYERSWAP_SWAP","SOCIAL_USERNAME_IN_USE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		responsesErrorCodeEnum = append(responsesErrorCodeEnum, v)
	}
}

func (m ResponsesErrorCode) validateResponsesErrorCodeEnum(path, location string, value ResponsesErrorCode) error {
	if err := validate.EnumCase(path, location, value, responsesErrorCodeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this responses error code
func (m ResponsesErrorCode) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateResponsesErrorCodeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this responses error code based on context it is used
func (m ResponsesErrorCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
