// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesVaultAccountSummaryResp responses vault account summary resp
//
// swagger:model responses.VaultAccountSummaryResp
type ResponsesVaultAccountSummaryResp struct {

	// Contract address of the vault
	// Example: 0x1234567890abcdef
	Address string `json:"address,omitempty"`

	// Unix timestamp in milliseconds of when the user joined the vault.
	// Example: 1717171717
	CreatedAt int64 `json:"created_at,omitempty"`

	// Amount deposited on the vault by the user in USDC
	// Example: 123.45
	DepositedAmount string `json:"deposited_amount,omitempty"`

	// Total P&L realized by the user in USD.
	// Example: 149.12
	TotalPnl string `json:"total_pnl,omitempty"`

	// Total ROI realized by the user in percentage, i.e. 0.1 means 10%.
	// Example: 0.724
	TotalRoi string `json:"total_roi,omitempty"`

	// Amount of vault tokens owned by the user
	// Example: 123.45
	VtokenAmount string `json:"vtoken_amount,omitempty"`
}

// Validate validates this responses vault account summary resp
func (m *ResponsesVaultAccountSummaryResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses vault account summary resp based on context it is used
func (m *ResponsesVaultAccountSummaryResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesVaultAccountSummaryResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesVaultAccountSummaryResp) UnmarshalBinary(b []byte) error {
	var res ResponsesVaultAccountSummaryResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
