// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesBBOResp responses b b o resp
//
// swagger:model responses.BBOResp
type ResponsesBBOResp struct {

	// Best ask price
	// Example: 30130.15
	Ask string `json:"ask,omitempty"`

	// Best ask size
	// Example: 0.05
	AskSize string `json:"ask_size,omitempty"`

	// Best bid price
	// Example: 30112.22
	Bid string `json:"bid,omitempty"`

	// Best bid size
	// Example: 0.04
	BidSize string `json:"bid_size,omitempty"`

	// Last update to the orderbook in milliseconds
	// Example: 1681493939981
	LastUpdatedAt int64 `json:"last_updated_at,omitempty"`

	// Symbol of the market
	// Example: BTC-USD-PERP
	Market string `json:"market,omitempty"`

	// Sequence number of the orderbook
	// Example: 20784
	SeqNo int64 `json:"seq_no,omitempty"`
}

// Validate validates this responses b b o resp
func (m *ResponsesBBOResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses b b o resp based on context it is used
func (m *ResponsesBBOResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesBBOResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesBBOResp) UnmarshalBinary(b []byte) error {
	var res ResponsesBBOResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
