// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesAccountHistoricalDataResp responses account historical data resp
//
// swagger:model responses.AccountHistoricalDataResp
type ResponsesAccountHistoricalDataResp struct {

	// Ordered list of datapoints
	Data []float64 `json:"data"`

	// Ordered list of timestamps
	Timestamps []int64 `json:"timestamps"`
}

// Validate validates this responses account historical data resp
func (m *ResponsesAccountHistoricalDataResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses account historical data resp based on context it is used
func (m *ResponsesAccountHistoricalDataResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesAccountHistoricalDataResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesAccountHistoricalDataResp) UnmarshalBinary(b []byte) error {
	var res ResponsesAccountHistoricalDataResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
