// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesVaultSummaryResp responses vault summary resp
//
// swagger:model responses.VaultSummaryResp
type ResponsesVaultSummaryResp struct {

	// Contract address of the vault
	// Example: 0x1234567890abcdef
	Address string `json:"address,omitempty"`

	// APR return of the vault in the last trailing month in percentage, i.e. 0.1 means 10%
	// Example: 0.023
	LastMonthReturn string `json:"last_month_return,omitempty"`

	// Max all time drawdown realized by the vault in percentage, i.e. 0.1 means 10%
	// Example: 0.1916
	MaxDrawdown string `json:"max_drawdown,omitempty"`

	// Max drawdown realized by the vault in the last 24 hours in percentage, i.e. 0.1 means 10%
	// Example: 0.0138
	MaxDrawdown24h string `json:"max_drawdown_24h,omitempty"`

	// Max drawdown realized by the vault in the last 30 days in percentage, i.e. 0.1 means 10%
	// Example: 0.1821
	MaxDrawdown30d string `json:"max_drawdown_30d,omitempty"`

	// Max drawdown realized by the vault in the last 7 days in percentage, i.e. 0.1 means 10%
	// Example: 0.1124
	MaxDrawdown7d string `json:"max_drawdown_7d,omitempty"`

	// Net deposits of the vault in USDC
	// Example: 1000000
	NetDeposits string `json:"net_deposits,omitempty"`

	// Number of depositors on the vault
	// Example: 100
	NumDepositors int64 `json:"num_depositors,omitempty"`

	// Vault equity of the owner (% of ownership) in percentage, i.e. 0.1 means 10%
	// Example: 0.145
	OwnerEquity string `json:"owner_equity,omitempty"`

	// P&L of the vault in the last 24 hours in USD
	// Example: 13.41
	Pnl24h string `json:"pnl_24h,omitempty"`

	// P&L of the vault in the last 30 days in USD
	// Example: 114.19
	Pnl30d string `json:"pnl_30d,omitempty"`

	// P&L of the vault in the last 7 days in USD
	// Example: 91.31
	Pnl7d string `json:"pnl_7d,omitempty"`

	// Return of the vault in the last 24 hours in percentage, i.e. 0.1 means 10%
	// Example: 0.034
	Roi24h string `json:"roi_24h,omitempty"`

	// Return of the vault in the last 30 days in percentage, i.e. 0.1 means 10%
	// Example: 0.003
	Roi30d string `json:"roi_30d,omitempty"`

	// Return of the vault in the last 7 days in percentage, i.e. 0.1 means 10%
	// Example: 0.123
	Roi7d string `json:"roi_7d,omitempty"`

	// Total P&L of the vault in USD
	// Example: 149.12
	TotalPnl string `json:"total_pnl,omitempty"`

	// Total ROI of the vault in percentage, i.e. 0.1 means 10%
	// Example: 0.724
	TotalRoi string `json:"total_roi,omitempty"`

	// Net deposits of the vault in USDC (deprecated; use net_deposits instead)
	// Example: 1000000
	Tvl string `json:"tvl,omitempty"`

	// All time volume traded by the vault in USD
	// Example: 12345678.16
	Volume string `json:"volume,omitempty"`

	// Volume traded by the vault in the last 24 hours in USD
	// Example: 45678.16
	Volume24h string `json:"volume_24h,omitempty"`

	// Volume traded by the vault in the last 30 days in USD
	// Example: 2345678.16
	Volume30d string `json:"volume_30d,omitempty"`

	// Volume traded by the vault in the last 7 days in USD
	// Example: 345678.16
	Volume7d string `json:"volume_7d,omitempty"`

	// Current value of vault token price in USD
	// Example: 1.23
	VtokenPrice string `json:"vtoken_price,omitempty"`

	// Total amount of available vault tokens
	// Example: 1000000
	VtokenSupply string `json:"vtoken_supply,omitempty"`
}

// Validate validates this responses vault summary resp
func (m *ResponsesVaultSummaryResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this responses vault summary resp based on context it is used
func (m *ResponsesVaultSummaryResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesVaultSummaryResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesVaultSummaryResp) UnmarshalBinary(b []byte) error {
	var res ResponsesVaultSummaryResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
