// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponsesErrorResponse responses error response
//
// swagger:model responses.ErrorResponse
type ResponsesErrorResponse struct {

	// error
	Error ResponsesErrorCode `json:"error,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this responses error response
func (m *ResponsesErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesErrorResponse) validateError(formats strfmt.Registry) error {
	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if err := m.Error.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("error")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("error")
		}
		return err
	}

	return nil
}

// ContextValidate validate this responses error response based on the context it is used
func (m *ResponsesErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateError(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResponsesErrorResponse) contextValidateError(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if err := m.Error.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("error")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("error")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ResponsesErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponsesErrorResponse) UnmarshalBinary(b []byte) error {
	var res ResponsesErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
